//! MSL (Metal Shading Language) code generator.
//!
//! Walks the MetalTile IR and emits valid MSL source text.
//! Handles constexpr params, tiled matmul, vectorized loads, and thread indexing.

pub(crate) mod config;
mod emit_block;
pub(crate) mod features;
mod fused;
mod helpers;
pub(crate) mod matmul;
pub(crate) mod preamble;
pub(crate) mod reduce;

use std::{collections::BTreeMap, fmt::Write};

pub use config::MslConfig;
use features::KernelFeatures;
use metaltile_core::{
    dtype::DType,
    ir::{Kernel, KernelMode, Op, ParamKind, ValueId},
};

use crate::{error::Result, passes, passes::type_check::infer_types};

#[macro_export]
macro_rules! wl {
    ($out:expr) => {{ let _ = writeln!($out); }};
    ($out:expr, $($arg:tt)*) => {{ let _ = writeln!($out, $($arg)*); }};
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Return `true` if any op in the kernel (body + all child blocks) is
/// `Op::ProgramId { axis }` for the given axis value.
fn kernel_uses_program_id_axis(kernel: &Kernel, axis: u32) -> bool {
    // Match either Op::ProgramId { axis } or a direct Op::Load { src: "tgid_y" }
    // (DSL kernels that use `tgid_y` directly instead of `program_id::<1>()`).
    let tgid_name = match axis {
        0 => "tgid_x",
        1 => "tgid_y",
        2 => "tgid_z",
        _ => "",
    };
    let check = |ops: &[Op]| {
        ops.iter().any(|op| match op {
            Op::ProgramId { axis: a } => *a == axis,
            Op::Load { src, indices, .. } => indices.is_empty() && src.as_str() == tgid_name,
            _ => false,
        })
    };
    check(&kernel.body.ops) || kernel.blocks.values().any(|b| check(&b.ops))
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

pub struct MslGenerator {
    config: MslConfig,
}

impl MslGenerator {
    pub fn new(config: MslConfig) -> Self { MslGenerator { config } }

    /// Like [`generate`] but also returns per-pass statistics.
    pub fn generate_with_stats(&self, kernel: &Kernel) -> Result<(String, Vec<passes::PassStats>)> {
        let mut k = kernel.clone();
        let stats = passes::run_passes_with_stats(&mut k, &passes::standard_pipeline())?;
        let msl = self.emit_msl(&k)?;
        Ok((msl, stats))
    }

    pub fn generate(&self, kernel: &Kernel) -> Result<String> {
        // Run the optimization pipeline on a clone before emitting.
        let mut k = kernel.clone();
        passes::run_passes_with_stats(&mut k, &passes::standard_pipeline())?;
        self.emit_msl(&k)
    }

    fn emit_msl(&self, k: &Kernel) -> Result<String> {
        let type_env = infer_types(k)?;
        let feat = self.analyze(k);
        let mut out = String::new();
        wl!(out, "// Generated by MetalTile");
        wl!(out, "#include <metal_stdlib>");
        wl!(out, "using namespace metal;");
        if feat.needs_bf16_struct && !self.config.native_bfloat {
            self.emit_bf16_preamble(&mut out);
        }
        if self.config.use_simd_matrix || feat.needs_simdgroup_matrix {
            wl!(out);
            wl!(out, "#include <metal_simdgroup_matrix>");
        }
        self.emit_activation_helpers(&feat, &mut out);
        wl!(out);
        self.emit_kernel(k, &feat, &type_env, &mut out)?;
        Ok(out)
    }

    // ---- kernel signature ------------------------------------------------

    fn emit_kernel(
        &self,
        kernel: &Kernel,
        feat: &KernelFeatures,
        type_env: &crate::passes::type_check::TypeEnv,
        out: &mut String,
    ) -> Result<()> {
        let mut buf_idx = 0u32;

        write!(out, "kernel void {}(", kernel.name).unwrap();

        // Tensor/Strided/Scalar params.
        for p in &kernel.params {
            match p.kind {
                ParamKind::Tensor => {
                    let q = if p.is_output { "device " } else { "const device " };
                    write!(
                        out,
                        "\n    {q}{} *{} [[buffer({buf_idx})]],",
                        self.msl_type_name(p.dtype),
                        p.name
                    )
                    .unwrap();
                    buf_idx += 1;
                },
                ParamKind::Strided => {
                    let q = if p.is_output { "device " } else { "const device " };
                    write!(
                        out,
                        "\n    {q}{} *{} [[buffer({buf_idx})]],",
                        self.msl_type_name(p.dtype),
                        p.name
                    )
                    .unwrap();
                    buf_idx += 1;
                    write!(out, "\n    constant uint *{}_shape [[buffer({buf_idx})]],", p.name)
                        .unwrap();
                    buf_idx += 1;
                    write!(out, "\n    constant uint *{}_strides [[buffer({buf_idx})]],", p.name)
                        .unwrap();
                    buf_idx += 1;
                },
                ParamKind::Scalar => {
                    write!(
                        out,
                        "\n    constant {} &{} [[buffer({buf_idx})]],",
                        self.msl_type_name(p.dtype),
                        p.name
                    )
                    .unwrap();
                    buf_idx += 1;
                },
            }
        }

        // Constexpr params.
        for ce in &kernel.constexprs {
            let msl_type = match ce.dtype {
                DType::F32 => "float",
                DType::F16 => "half",
                DType::BF16 => "float",
                DType::I32 => "int",
                DType::I64 => "long",
                DType::U64 => "ulong",
                _ => "uint",
            };
            write!(out, "\n    constant {msl_type} &{} [[buffer({buf_idx})]],", ce.name.name())
                .unwrap();
            buf_idx += 1;
        }

        // Thread / threadgroup position attributes.
        match kernel.mode {
            KernelMode::Elementwise => {
                write!(out, "\n    uint tid [[thread_position_in_grid]]").unwrap();
            },
            KernelMode::Reduction => {
                write!(out, "\n    uint3 _tid3  [[thread_position_in_threadgroup]],").unwrap();
                write!(out, "\n    uint3 _tgid3 [[threadgroup_position_in_grid]],").unwrap();
                write!(out, "\n    uint3 _lsize3 [[threads_per_threadgroup]]").unwrap();
            },
            KernelMode::Grid3D => {
                write!(out, "\n    uint3 gid [[thread_position_in_grid]]").unwrap();
            },
            KernelMode::Tile2D => {
                write!(out, "\n    uint2 tid  [[thread_position_in_threadgroup]],").unwrap();
                write!(out, "\n    uint2 tgid [[threadgroup_position_in_grid]]").unwrap();
            },
            KernelMode::SimdGroup2D => {
                write!(out, "\n    uint3 lid [[thread_position_in_threadgroup]],").unwrap();
                write!(out, "\n    uint3 tid [[threadgroup_position_in_grid]]").unwrap();
                write!(out, ",\n    uint simd_lane [[thread_index_in_simdgroup]]").unwrap();
                write!(out, ",\n    uint simd_group [[simdgroup_index_in_threadgroup]]").unwrap();
            },
        }
        // NOTE: SimdGroup2D mode emits simd_lane and simd_group inline above.
        // Other modes add them conditionally here.
        if feat.needs_simd_lane && !matches!(kernel.mode, KernelMode::SimdGroup2D) {
            write!(out, ",\n    uint simd_lane [[thread_index_in_simdgroup]]").unwrap();
        }
        if feat.needs_simd_group && !matches!(kernel.mode, KernelMode::SimdGroup2D) {
            write!(out, ",\n    uint simd_group [[simdgroup_index_in_threadgroup]]").unwrap();
        }

        wl!(out, "\n) {{");

        // Inject scalar aliases for Reduction mode.
        // `tgid_y` is only emitted when the kernel references program_id::<1>(),
        // avoiding -Wunused-variable on single-axis reduction kernels.
        if kernel.mode == KernelMode::Reduction {
            wl!(out, "    uint tid    = _tid3.x;");
            wl!(out, "    uint tgid_x = _tgid3.x;");
            if kernel_uses_program_id_axis(kernel, 1) {
                wl!(out, "    uint tgid_y = _tgid3.y;");
            }
            wl!(out, "    uint lsize  = _lsize3.x;");
            if feat.needs_simd_group {
                wl!(out, "    uint n_simd = lsize / 32u;");
            }
        }

        // Two-pass: collect threadgroup hoists first, then emit body.
        let mut body_buf = String::new();
        let mut hoists: Vec<String> = Vec::new();
        let extra_names: BTreeMap<ValueId, String> = BTreeMap::new();

        if feat.is_matmul {
            self.emit_tiled(&mut body_buf, "    ", kernel, None)?;
        } else {
            self.emit_block(
                &kernel.body,
                &kernel.blocks,
                &mut body_buf,
                1,
                kernel,
                type_env,
                &extra_names,
                &mut hoists,
            )?;
        }

        for h in &hoists {
            wl!(out, "    {h}");
        }
        if !hoists.is_empty() {
            wl!(out);
        }
        out.push_str(&body_buf);

        wl!(out, "}}");
        Ok(())
    }
}

impl Default for MslGenerator {
    fn default() -> Self { MslGenerator::new(MslConfig::default()) }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use metaltile_core::{
        dtype::DType,
        ir::{BinOpKind, IndexExpr, Kernel, Op, Param, ValueId},
        shape::Shape,
    };

    use super::*;

    fn make_vadd() -> Kernel {
        let mut k = Kernel::new("vector_add");
        k.params.push(Param {
            name: "a".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: false,
            kind: Default::default(),
        });
        k.params.push(Param {
            name: "b".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: false,
            kind: Default::default(),
        });
        k.params.push(Param {
            name: "c".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: true,
            kind: Default::default(),
        });
        k.body.push_op(Op::ProgramId { axis: 0 }, ValueId::new(0));
        k.body.name_value(ValueId::new(0), "idx");
        k.body.push_op(
            Op::Load {
                src: "a".into(),
                mask: None,
                other: None,
                indices: vec![IndexExpr::Value(ValueId::new(0))],
            },
            ValueId::new(1),
        );
        k.body.name_value(ValueId::new(1), "x");
        k.body.push_op(
            Op::Load {
                src: "b".into(),
                mask: None,
                other: None,
                indices: vec![IndexExpr::Value(ValueId::new(0))],
            },
            ValueId::new(2),
        );
        k.body.name_value(ValueId::new(2), "y");
        k.body.push_op(
            Op::BinOp { op: BinOpKind::Add, lhs: ValueId::new(1), rhs: ValueId::new(2) },
            ValueId::new(3),
        );
        k.body.name_value(ValueId::new(3), "sum");
        k.body.push_op_no_result(Op::Store {
            mask: None,
            dst: "c".into(),
            indices: vec![IndexExpr::Value(ValueId::new(0))],
            value: ValueId::new(3),
        });
        k
    }

    #[test]
    fn vadd_msl_structure() {
        let k = make_vadd();
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("kernel void vector_add"), "missing kernel declaration");
        assert!(msl.contains("const device float *a [[buffer(0)]]"), "missing param a");
        assert!(msl.contains("const device float *b [[buffer(1)]]"), "missing param b");
        assert!(msl.contains("device float *c [[buffer(2)]]"), "missing output param c");
        assert!(msl.contains("uint tid [[thread_position_in_grid]]"), "missing scalar tid");
        assert!(!msl.contains("tid.x"), "scalar kernel must not use tid.x");
    }

    #[test]
    fn vadd_msl_load_store() {
        let k = make_vadd();
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("v_idx"), "program_id should map to tid");
        assert!(msl.contains("a[v_idx]"), "load from a at idx");
        assert!(msl.contains("b[v_idx]"), "load from b at idx");
        assert!(msl.contains("v_x + v_y"), "add x and y");
        assert!(msl.contains("c[v_idx] = v_sum"), "store sum to c");
    }

    #[test]
    fn const_op_emits_uint_for_nonneg() {
        let mut k = Kernel::new("const_test");
        k.body.push_op(Op::Const { value: 42 }, ValueId::new(0));
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("uint v0 = 42u"), "non-negative Const should emit as uint");
    }

    #[test]
    fn const_op_emits_int_for_negative() {
        let mut k = Kernel::new("const_neg_test");
        k.body.push_op(Op::Const { value: -7 }, ValueId::new(0));
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("int v0 = -7"), "negative Const should emit as int");
    }

    #[test]
    fn cast_op_emits_static_cast() {
        let mut k = Kernel::new("cast_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::F16 }, ValueId::new(1));
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("static_cast<half>"), "cast to f16 should use static_cast<half>");
    }

    #[test]
    fn native_bfloat_omits_compat_preamble() {
        let mut k = Kernel::new("native_bfloat_param");
        k.params.push(Param {
            name: "a".into(),
            dtype: DType::BF16,
            shape: Shape::scalar(),
            is_output: false,
            kind: Default::default(),
        });
        let msl = MslGenerator::new(MslConfig { native_bfloat: true, ..MslConfig::default() })
            .generate(&k)
            .unwrap();
        assert!(
            !msl.contains("struct bfloat16_t"),
            "native bfloat mode must not emit the compatibility preamble"
        );
        assert!(
            msl.contains("const device bfloat *a [[buffer(0)]]"),
            "native bfloat mode should keep native buffer types"
        );
    }

    #[test]
    fn bf16_cast_uses_compat_ctor_when_native_bfloat_disabled() {
        let mut k = Kernel::new("compat_bf16_cast");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::BF16 }, ValueId::new(1));
        let msl = MslGenerator::new(MslConfig { native_bfloat: false, ..MslConfig::default() })
            .generate(&k)
            .unwrap();
        assert!(msl.contains("struct bfloat16_t"), "compat mode should emit the bfloat16_t helper");
        assert!(
            msl.contains("bfloat16_t v1 = bfloat16_t(v0);"),
            "compat mode should cast to the compatibility struct"
        );
    }

    #[test]
    fn bf16_cast_uses_native_static_cast_when_enabled() {
        let mut k = Kernel::new("native_bf16_cast");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::BF16 }, ValueId::new(1));
        let msl = MslGenerator::new(MslConfig { native_bfloat: true, ..MslConfig::default() })
            .generate(&k)
            .unwrap();
        assert!(
            !msl.contains("struct bfloat16_t"),
            "native mode should not emit the compatibility helper"
        );
        assert!(
            msl.contains("bfloat v1 = bfloat(v0);"),
            "native mode should cast directly to bfloat via constructor"
        );
    }

    #[test]
    fn unary_op_emit() {
        use metaltile_core::ir::UnaryOpKind;
        let mut k = Kernel::new("unary_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body
            .push_op(Op::UnaryOp { op: UnaryOpKind::Exp, value: ValueId::new(0) }, ValueId::new(1));
        k.body.name_value(ValueId::new(1), "r");
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("exp(v0)"), "exp unary op");
        assert!(msl.contains("v_r"), "named result");
    }

    #[test]
    fn activation_silu_emits_helper() {
        use metaltile_core::ir::ActKind;
        let mut k = Kernel::new("silu_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(
            Op::Activation { kind: ActKind::Silu, value: ValueId::new(0) },
            ValueId::new(1),
        );
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("mt_silu"), "silu helper function name");
        assert!(msl.contains("inline T mt_silu"), "silu helper definition");
    }

    #[test]
    fn select_emit() {
        let mut k = Kernel::new("select_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Const { value: 2 }, ValueId::new(1));
        k.body.push_op(Op::Const { value: 3 }, ValueId::new(2));
        k.body.push_op(
            Op::Select {
                cond: ValueId::new(0),
                on_true: ValueId::new(1),
                on_false: ValueId::new(2),
            },
            ValueId::new(3),
        );
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("bool("), "bool cast on condition");
        assert!(msl.contains("? v1 : v2"), "ternary select");
    }

    #[test]
    fn multi_dim_load_stride() {
        use metaltile_core::{constexpr::ConstExpr, shape::Dim};
        let mut k = Kernel::new("matload_test");
        let m_ce = ConstExpr::new("M");
        let n_ce = ConstExpr::new("N");
        k.params.push(Param {
            name: "a".into(),
            dtype: DType::F32,
            shape: Shape::new([Dim::ConstExpr(m_ce.clone()), Dim::ConstExpr(n_ce.clone())]),
            is_output: false,
            kind: Default::default(),
        });
        k.params.push(Param {
            name: "out".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: true,
            kind: Default::default(),
        });
        k.constexprs.push(metaltile_core::ir::ConstExprDecl {
            name: m_ce,
            dtype: DType::U32,
            value: None,
        });
        k.constexprs.push(metaltile_core::ir::ConstExprDecl {
            name: n_ce,
            dtype: DType::U32,
            value: None,
        });
        k.body.push_op(Op::Const { value: 0 }, ValueId::new(0));
        k.body.name_value(ValueId::new(0), "row");
        k.body.push_op(Op::Const { value: 0 }, ValueId::new(1));
        k.body.name_value(ValueId::new(1), "col");
        k.body.push_op(
            Op::Load {
                mask: None,
                other: None,
                src: "a".into(),
                indices: vec![IndexExpr::Value(ValueId::new(0)), IndexExpr::Value(ValueId::new(1))],
            },
            ValueId::new(2),
        );
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("(v_row) * N + (v_col)"), "2D load must use row-major stride");
    }

    #[test]
    fn fusion_cast_exp_binop_into_single_expression() {
        use metaltile_core::ir::{BinOpKind, UnaryOpKind};

        use crate::passes::{Pass, fusion::FusionPass};

        let mut k = Kernel::new("fused_test");
        k.body.push_op(Op::Const { value: 3 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::F32 }, ValueId::new(1));
        k.body
            .push_op(Op::UnaryOp { op: UnaryOpKind::Exp, value: ValueId::new(1) }, ValueId::new(2));
        k.body.push_op(Op::Const { value: 2 }, ValueId::new(3));
        k.body.push_op(
            Op::BinOp { op: BinOpKind::Mul, lhs: ValueId::new(2), rhs: ValueId::new(3) },
            ValueId::new(4),
        );
        FusionPass.run(&mut k).unwrap();
        let has_fused = k.body.ops.iter().any(|op| matches!(op, Op::FusedElementwise { .. }));
        assert!(has_fused, "fusion pass should create a FusedElementwise op");
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(
            msl.contains("exp") && msl.contains(" * "),
            "fused expression should contain exp and mul"
        );
        let lines: Vec<&str> = msl.lines().collect();
        let fused_line = lines.iter().find(|l| l.contains("v4")).unwrap();
        assert!(
            fused_line.contains("exp") && fused_line.contains("static_cast"),
            "single fused line should contain both exp and cast: {}",
            fused_line
        );
        assert!(!msl.contains("v1 = "), "no separate declaration for v1");
        assert!(!msl.contains("v2 = "), "no separate declaration for v2");
    }

    #[test]
    fn reduction_preamble_omits_tgid_y_when_unused() {
        let mut k = Kernel::new("reduction_no_y");
        k.mode = KernelMode::Reduction;
        // axis-0 only → tgid_y should NOT be emitted
        k.body.push_op(Op::ProgramId { axis: 0 }, ValueId::new(0));
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(!msl.contains("tgid_y"), "tgid_y must be omitted when program_id axis 1 is unused");
    }

    #[test]
    fn reduction_preamble_emits_tgid_y_when_used() {
        let mut k = Kernel::new("reduction_with_y");
        k.mode = KernelMode::Reduction;
        k.body.push_op(Op::ProgramId { axis: 0 }, ValueId::new(0));
        k.body.push_op(Op::ProgramId { axis: 1 }, ValueId::new(1));
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("tgid_y"), "tgid_y must be emitted when program_id axis 1 is used");
    }
}
