//! MSL (Metal Shading Language) code generator.
//!
//! Walks the MetalTile IR and emits valid MSL source text.
//! Handles constexpr params, tiled matmul, vectorized loads, and thread indexing.

use std::{collections::BTreeMap, fmt::Write};

use metaltile_core::{
    dtype::DType,
    ir::{
        ActKind,
        BinOpKind,
        Block,
        BlockId,
        IndexExpr,
        Kernel,
        KernelMode,
        Op,
        ParamKind,
        ReduceKind,
        UnaryOpKind,
        ValueId,
    },
    shape::{Dim, Shape},
};

use crate::{
    error::Result,
    passes,
    passes::{
        tile_lowering::TileSchedule,
        type_check::{TypeEnv, infer_types},
    },
};

macro_rules! wl {
    ($out:expr) => {{ let _ = writeln!($out); }};
    ($out:expr, $($arg:tt)*) => {{ let _ = writeln!($out, $($arg)*); }};
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
pub struct MslConfig {
    pub simd_size: u32,
    /// Emit `simdgroup_multiply_accumulate` (requires Metal GPU family 9 / M3+).
    pub use_simd_matrix: bool,
    pub debug_comments: bool,
    /// Use native `bfloat` type (Metal 3.1+, M3+). When false, uses `bfloat16_t` struct.
    pub native_bfloat: bool,
    /// Emit `async_copy` prefetch (requires Metal 3 / M2+).
    pub async_copy: bool,
    pub tile_schedule: TileSchedule,
}

impl Default for MslConfig {
    fn default() -> Self {
        MslConfig {
            simd_size: 32,
            use_simd_matrix: false,
            debug_comments: false,
            native_bfloat: true,
            async_copy: false,
            tile_schedule: TileSchedule::default(),
        }
    }
}

// ---------------------------------------------------------------------------
// Kernel feature analysis
// ---------------------------------------------------------------------------

struct KernelFeatures {
    has_tile: bool,
    is_matmul: bool,
    needs_simd_lane: bool,
    needs_simd_group: bool, // needs simdgroup_index_in_threadgroup (for inter-warp reduction)
    needs_bf16_struct: bool,
    needs_silu: bool,
    needs_gelu: bool,
    needs_relu: bool,
    needs_sigmoid: bool,
    needs_erf: bool,
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

pub struct MslGenerator {
    config: MslConfig,
}

impl MslGenerator {
    pub fn new(config: MslConfig) -> Self { MslGenerator { config } }

    pub fn generate(&self, kernel: &Kernel) -> Result<String> {
        // Run the optimization pipeline on a clone before emitting.
        let mut k = kernel.clone();
        passes::run_passes(&mut k, &passes::standard_pipeline())?;

        let type_env = infer_types(&k)?;
        let feat = self.analyze(&k);
        let mut out = String::new();
        wl!(out, "// Generated by MetalTile");
        wl!(out, "#include <metal_stdlib>");
        wl!(out, "using namespace metal;");
        if feat.needs_bf16_struct && !self.config.native_bfloat {
            self.emit_bf16_preamble(&mut out);
        }
        if self.config.use_simd_matrix {
            wl!(out);
            wl!(out, "#if __METAL_VERSION__ >= 310");
            wl!(out, "#include <metal_simdgroup_matrix>");
            wl!(out, "#endif");
        }
        self.emit_activation_helpers(&feat, &mut out);
        wl!(out);
        self.emit_kernel(&k, &feat, &type_env, &mut out)?;
        Ok(out)
    }

    // ---- feature analysis ------------------------------------------------

    fn analyze(&self, kernel: &Kernel) -> KernelFeatures {
        let mut feat = KernelFeatures {
            has_tile: false,
            is_matmul: false,
            needs_simd_lane: false,
            needs_simd_group: false,
            needs_bf16_struct: false,
            needs_silu: false,
            needs_gelu: false,
            needs_relu: false,
            needs_sigmoid: false,
            needs_erf: false,
        };
        for p in &kernel.params {
            if p.dtype == DType::BF16 {
                feat.needs_bf16_struct = true;
            }
        }
        self.analyze_block(&kernel.body, &mut feat);
        for (_, block) in &kernel.blocks {
            self.analyze_block(block, &mut feat);
        }
        let tensor_2d = kernel.params.iter().filter(|p| p.shape.rank() == 2).count();
        feat.is_matmul = feat.has_tile && tensor_2d >= 2;

        feat
    }

    fn analyze_block(&self, block: &Block, feat: &mut KernelFeatures) {
        for op in &block.ops {
            match op {
                Op::Dot { .. } => feat.has_tile = true,
                Op::Reduce { .. } | Op::Scan { .. } => {
                    feat.needs_simd_lane = true;
                    feat.needs_simd_group = true;
                },
                Op::Load { src, indices, .. } if indices.is_empty() => {
                    if src == "simd_lane" {
                        feat.needs_simd_lane = true;
                    }
                    if src == "simd_id" {
                        feat.needs_simd_group = true;
                    }
                },
                Op::Zeros { dtype, .. } | Op::Splat { dtype, .. } =>
                    if *dtype == DType::BF16 {
                        feat.needs_bf16_struct = true;
                    },
                Op::Cast { dtype, .. } =>
                    if *dtype == DType::BF16 {
                        feat.needs_bf16_struct = true;
                    },
                Op::Activation { kind, .. } => match kind {
                    ActKind::Silu => feat.needs_silu = true,
                    ActKind::Gelu => feat.needs_gelu = true,
                    ActKind::Relu => feat.needs_relu = true,
                    ActKind::Sigmoid => feat.needs_sigmoid = true,
                    ActKind::Tanh => {},
                },
                Op::UnaryOp { op: UnaryOpKind::Erf, .. } => feat.needs_erf = true,
                _ => {},
            }
        }
    }

    // ---- preamble helpers ------------------------------------------------

    fn emit_bf16_preamble(&self, out: &mut String) {
        wl!(out);
        wl!(out, "// BF16 compatibility struct for pre-Metal-3.1 targets");
        wl!(out, "struct bfloat16_t {{");
        wl!(out, "    uint16_t bits;");
        wl!(out, "    bfloat16_t() = default;");
        wl!(out, "    bfloat16_t(float v) {{");
        wl!(out, "        uint32_t x = as_type<uint32_t>(v);");
        wl!(out, "        bits = uint16_t((x + 0x7FFFu + ((x >> 16) & 1u)) >> 16);");
        wl!(out, "    }}");
        wl!(out, "    operator float() const {{");
        wl!(out, "        return as_type<float>(uint32_t(bits) << 16);");
        wl!(out, "    }}");
        wl!(out, "    operator float() const device {{");
        wl!(out, "        return as_type<float>(uint32_t(bits) << 16);");
        wl!(out, "    }}");
        wl!(out, "    operator float() const threadgroup {{");
        wl!(out, "        return as_type<float>(uint32_t(bits) << 16);");
        wl!(out, "    }}");
        wl!(out, "}};");
    }

    fn msl_type_name(&self, dtype: DType) -> &'static str {
        if dtype == DType::BF16 && !self.config.native_bfloat {
            "bfloat16_t"
        } else {
            dtype.msl_name()
        }
    }

    fn emit_cast_expr(&self, dtype: DType, value: &str) -> String {
        if dtype == DType::BF16 {
            // bfloat16_t(v) for compat struct, bfloat(v) for native Metal 3.1+.
            // static_cast<bfloat> is unreliable in Metal; use constructor-style cast.
            format!("{}({value})", self.msl_type_name(dtype))
        } else {
            format!("static_cast<{}>({value})", self.msl_type_name(dtype))
        }
    }

    fn emit_activation_helpers(&self, feat: &KernelFeatures, out: &mut String) {
        if feat.needs_silu {
            wl!(out);
            wl!(out, "template<typename T>");
            wl!(out, "inline T mt_silu(T x) {{ return x / (T(1) + exp(-x)); }}");
        }
        if feat.needs_gelu {
            wl!(out);
            wl!(out, "template<typename T>");
            wl!(out, "inline T mt_gelu(T x) {{");
            wl!(out, "    const T k = T(0.7978845608f);");
            wl!(out, "    return T(0.5f) * x * (T(1) + tanh(k * (x + T(0.044715f) * x*x*x)));");
            wl!(out, "}}");
        }
        if feat.needs_relu {
            wl!(out);
            wl!(out, "template<typename T>");
            wl!(out, "inline T mt_relu(T x) {{ return max(T(0), x); }}");
        }
        if feat.needs_sigmoid {
            wl!(out);
            wl!(out, "template<typename T>");
            wl!(out, "inline T mt_sigmoid(T x) {{ return T(1) / (T(1) + exp(-x)); }}");
        }
        if feat.needs_erf {
            wl!(out);
            // Polynomial approximation matching MLX erf.h (max error < 1 ulp)
            wl!(out, "inline float mt_erf_impl(float a) {{");
            wl!(out, "    float r, s, t, u;");
            wl!(out, "    t = metal::abs(a);");
            wl!(out, "    s = a * a;");
            wl!(out, "    if (t > 0.927734375f) {{");
            wl!(out, "        r = metal::fma(-1.72853470e-5f, t, 3.83197126e-4f);");
            wl!(out, "        u = metal::fma(-3.88396438e-3f, t, 2.42546219e-2f);");
            wl!(out, "        r = metal::fma(r, s, u);");
            wl!(out, "        r = metal::fma(r, t, -1.06777877e-1f);");
            wl!(out, "        r = metal::fma(r, t, -6.34846687e-1f);");
            wl!(out, "        r = metal::fma(r, t, -1.28717512e-1f);");
            wl!(out, "        r = metal::fma(r, t, -t);");
            wl!(out, "        r = -(exp(r) - 1.0f);");
            wl!(out, "        r = metal::copysign(r, a);");
            wl!(out, "    }} else {{");
            wl!(out, "        r = -5.96761703e-4f;");
            wl!(out, "        r = metal::fma(r, s,  4.99119423e-3f);");
            wl!(out, "        r = metal::fma(r, s, -2.67681349e-2f);");
            wl!(out, "        r = metal::fma(r, s,  1.12819925e-1f);");
            wl!(out, "        r = metal::fma(r, s, -3.76125336e-1f);");
            wl!(out, "        r = metal::fma(r, s,  1.28379166e-1f);");
            wl!(out, "        r = metal::fma(r, a, a);");
            wl!(out, "    }}");
            wl!(out, "    return r;");
            wl!(out, "}}");
            wl!(out, "template<typename T>");
            wl!(out, "inline T mt_erf_impl(T x) {{ return T(mt_erf_impl(float(x))); }}");
        }
    }

    // ---- kernel signature ------------------------------------------------

    fn emit_kernel(
        &self,
        kernel: &Kernel,
        feat: &KernelFeatures,
        type_env: &TypeEnv,
        out: &mut String,
    ) -> Result<()> {
        let mut buf_idx = 0u32;

        write!(out, "kernel void {}(", kernel.name).unwrap();

        // Tensor/Strided/Scalar params — always followed by something, so always comma-terminate.
        for p in &kernel.params {
            match p.kind {
                ParamKind::Tensor => {
                    let q = if p.is_output { "device " } else { "const device " };
                    write!(
                        out,
                        "\n    {q}{} *{} [[buffer({buf_idx})]],",
                        self.msl_type_name(p.dtype),
                        p.name
                    )
                    .unwrap();
                    buf_idx += 1;
                },
                ParamKind::Strided => {
                    let q = if p.is_output { "device " } else { "const device " };
                    write!(
                        out,
                        "\n    {q}{} *{} [[buffer({buf_idx})]],",
                        self.msl_type_name(p.dtype),
                        p.name
                    )
                    .unwrap();
                    buf_idx += 1;
                    write!(out, "\n    constant uint *{}_shape [[buffer({buf_idx})]],", p.name)
                        .unwrap();
                    buf_idx += 1;
                    write!(out, "\n    constant uint *{}_strides [[buffer({buf_idx})]],", p.name)
                        .unwrap();
                    buf_idx += 1;
                },
                ParamKind::Scalar => {
                    write!(
                        out,
                        "\n    constant {} &{} [[buffer({buf_idx})]],",
                        self.msl_type_name(p.dtype),
                        p.name
                    )
                    .unwrap();
                    buf_idx += 1;
                },
            }
        }

        // Constexpr params.
        for ce in &kernel.constexprs {
            let msl_type = match ce.dtype {
                DType::F32 => "float",
                DType::F16 => "half",
                DType::BF16 => "float", // Metal BF16 as float for constants
                DType::I32 => "int",
                DType::I64 => "long",
                DType::U64 => "ulong",
                _ => "uint",
            };
            write!(out, "\n    constant {msl_type} &{} [[buffer({buf_idx})]],", ce.name.name())
                .unwrap();
            buf_idx += 1;
        }

        // Thread / threadgroup position attributes — all built-ins must share
        // the same vector width (Metal constraint), so each mode is self-contained.
        match kernel.mode {
            KernelMode::Elementwise => {
                write!(out, "\n    uint tid [[thread_position_in_grid]]").unwrap();
            },
            KernelMode::Reduction => {
                write!(out, "\n    uint3 _tid3  [[thread_position_in_threadgroup]],").unwrap();
                write!(out, "\n    uint3 _tgid3 [[threadgroup_position_in_grid]],").unwrap();
                write!(out, "\n    uint3 _lsize3 [[threads_per_threadgroup]]").unwrap();
            },
            KernelMode::Grid3D => {
                write!(out, "\n    uint3 gid [[thread_position_in_grid]]").unwrap();
            },
            KernelMode::Tile2D => {
                write!(out, "\n    uint2 tid  [[thread_position_in_threadgroup]],").unwrap();
                write!(out, "\n    uint2 tgid [[threadgroup_position_in_grid]]").unwrap();
            },
        }
        if feat.needs_simd_lane {
            write!(out, ",\n    uint simd_lane [[thread_index_in_simdgroup]]").unwrap();
        }
        if feat.needs_simd_group && !feat.is_matmul {
            write!(out, ",\n    uint simd_id [[simdgroup_index_in_threadgroup]]").unwrap();
        }
        if self.config.use_simd_matrix && feat.is_matmul {
            write!(out, ",\n    uint simd_group [[simdgroup_index_in_threadgroup]]").unwrap();
            write!(out, ",\n    uint simd_lane [[thread_index_in_simdgroup]]").unwrap();
        }

        wl!(out, "\n) {{");

        // Inject scalar aliases for the Reduction mode so the body can use
        // `tid`, `tgid_x`, `tgid_y`, `lsize`, and `n_simd` directly.
        if kernel.mode == KernelMode::Reduction {
            wl!(out, "    uint tid    = _tid3.x;");
            wl!(out, "    uint tgid_x = _tgid3.x;");
            wl!(out, "    uint tgid_y = _tgid3.y;");
            wl!(out, "    uint lsize  = _lsize3.x;");
            if feat.needs_simd_group {
                wl!(out, "    uint n_simd = lsize / 32u;");
            }
        }

        // Two-pass: collect threadgroup hoists first, then emit body.
        let mut body_buf = String::new();
        let mut hoists: Vec<String> = Vec::new();
        let extra_names: BTreeMap<ValueId, String> = BTreeMap::new();

        if feat.is_matmul {
            self.emit_tiled(&mut body_buf, "    ", kernel, None)?;
        } else {
            self.emit_block(
                &kernel.body,
                &kernel.blocks,
                &mut body_buf,
                1,
                kernel,
                type_env,
                &extra_names,
                &mut hoists,
            )?;
        }

        for h in &hoists {
            wl!(out, "    {h}");
        }
        if !hoists.is_empty() {
            wl!(out);
        }
        out.push_str(&body_buf);

        wl!(out, "}}");
        Ok(())
    }

    // ---- block emission --------------------------------------------------

    #[allow(clippy::too_many_arguments)]
    fn emit_block(
        &self,
        block: &Block,
        all_blocks: &BTreeMap<BlockId, Block>,
        out: &mut String,
        indent: usize,
        kernel: &Kernel,
        type_env: &TypeEnv,
        extra_names: &BTreeMap<ValueId, String>,
        hoists: &mut Vec<String>,
    ) -> Result<()> {
        let has_tile = matches!(kernel.mode, KernelMode::Tile2D);
        let pad = "    ".repeat(indent);

        if self.config.debug_comments {
            // Emit a comment per op if debug mode is on.
            // We'll emit inline comments alongside the ops below.
        }

        for (i, op) in block.ops.iter().enumerate() {
            let vid = block.results.get(i).and_then(|x| *x);

            match op {
                // ---- indexing ------------------------------------------
                Op::ProgramId { axis } => {
                    let v = self.vname(vid, block, extra_names);
                    match kernel.mode {
                        KernelMode::Elementwise => match axis {
                            0 => wl!(out, "{pad}uint {v} = tid;"),
                            _ => wl!(out, "{pad}uint {v} = 0;"),
                        },
                        KernelMode::Reduction => match axis {
                            0 => wl!(out, "{pad}uint {v} = tgid_x;"),
                            1 => wl!(out, "{pad}uint {v} = tgid_y;"),
                            _ => wl!(out, "{pad}uint {v} = 0;"),
                        },
                        KernelMode::Grid3D => match axis {
                            0 => wl!(out, "{pad}uint {v} = gid.x;"),
                            1 => wl!(out, "{pad}uint {v} = gid.y;"),
                            2 => wl!(out, "{pad}uint {v} = gid.z;"),
                            _ => wl!(out, "{pad}uint {v} = 0;"),
                        },
                        KernelMode::Tile2D => match axis {
                            0 => wl!(out, "{pad}uint {v} = tgid.x;"),
                            1 => wl!(out, "{pad}uint {v} = tgid.y;"),
                            _ => wl!(out, "{pad}uint {v} = 0;"),
                        },
                    }
                },

                Op::Const { value } => {
                    let v = self.vname(vid, block, extra_names);
                    wl!(out, "{pad}int {v} = {value};");
                },

                Op::Arange { start, step, len } => {
                    let v = self.vname(vid, block, extra_names);
                    let s0 = start.unwrap_or(0.0);
                    let ds = step.unwrap_or(1.0);
                    // Each thread gets its own position within the arange range.
                    let raw_idx = if has_tile {
                        format!("(tid.y * {len} + tid.x) % {len}")
                    } else if kernel.mode == KernelMode::Grid3D {
                        format!("gid.x % {len}")
                    } else {
                        format!("tid % {len}")
                    };
                    if s0 == 0.0 && ds == 1.0 {
                        wl!(out, "{pad}uint {v} = {raw_idx};");
                    } else {
                        wl!(out, "{pad}float {v} = {s0}f + float({raw_idx}) * {ds}f;");
                    }
                },

                // ---- memory --------------------------------------------
                Op::Load { src, indices, .. } => {
                    let v = self.vname(vid, block, extra_names);
                    // Elementwise kernels operate on BF16 values without explicit casts in the
                    // DSL (e.g. `abs(load(a[idx]))`). With native bfloat in Metal 3.1+, there
                    // is no abs(bfloat)/max(bfloat,...)/etc. overload, so the call is ambiguous.
                    // Fix: promote BF16 to float at load time for Elementwise kernels.
                    //
                    // Reduction kernels (softmax, rms_norm, etc.) explicitly call .cast::<f32>()
                    // in the DSL after loading, so they don't need promotion at load time —
                    // and leaving the type as bfloat lets the compiler vectorize 4 consecutive
                    // 16-bit loads into a single bfloat4 memory transaction.
                    let src_dtype = kernel.params.iter().find(|p| p.name == *src).map(|p| p.dtype);
                    let promote_bf16 = self.config.native_bfloat
                        && src_dtype == Some(DType::BF16)
                        && kernel.mode == KernelMode::Elementwise;
                    if indices.is_empty() {
                        if promote_bf16 {
                            wl!(out, "{pad}float {v} = float({src});");
                        } else {
                            wl!(out, "{pad}auto {v} = {src};");
                        }
                    } else {
                        let idx = self.emit_idx(indices, block, extra_names, kernel, src);
                        if promote_bf16 {
                            wl!(out, "{pad}float {v} = float({src}[{idx}]);");
                        } else {
                            wl!(out, "{pad}auto {v} = {src}[{idx}];");
                        }
                    }
                },

                Op::Store { dst, indices, value, .. } => {
                    let idx = self.emit_idx(indices, block, extra_names, kernel, dst);
                    let val = self.vname(Some(*value), block, extra_names);
                    // With native bfloat, Metal won't auto-convert float→bfloat on store.
                    let dst_dtype = kernel.params.iter().find(|p| p.name == *dst).map(|p| p.dtype);
                    if self.config.native_bfloat && dst_dtype == Some(DType::BF16) {
                        wl!(out, "{pad}{dst}[{idx}] = bfloat({val});");
                    } else {
                        wl!(out, "{pad}{dst}[{idx}] = {val};");
                    }
                },

                Op::Zeros { dtype, shape } => {
                    let v = self.vname(vid, block, extra_names);
                    let (decl, init_lines) = self.emit_tile_alloc(dtype, shape, &v, 0.0);
                    wl!(out, "{pad}{decl};");
                    for line in &init_lines {
                        wl!(out, "{pad}{line}");
                    }
                },

                Op::Splat { value: sv, dtype, shape } => {
                    let v = self.vname(vid, block, extra_names);
                    let (decl, _) = self.emit_tile_alloc(dtype, shape, &v, *sv);
                    let lit = fmt_float(*sv, dtype);
                    wl!(out, "{pad}{decl};");
                    match shape.num_elements() {
                        Some(1) | None if shape.rank() == 0 => {
                            wl!(out, "{pad}{v} = {lit};");
                        },
                        _ => {
                            let n = self.shape_nelems_str(shape);
                            wl!(out, "{pad}for (uint _i = 0; _i < {n}; _i++) {v}[_i] = {lit};");
                        },
                    }
                },

                Op::Slice { value, ranges } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    // Compute the stride-aware offset using the type environment.
                    let offset_str = type_env
                        .get(value)
                        .and_then(|tv| {
                            let shape = &tv.shape;
                            let rank = shape.rank();
                            if rank <= 1 {
                                None
                            } else {
                                let mut parts: Vec<String> = Vec::new();
                                for &(axis, start, _len) in ranges {
                                    if start == 0 {
                                        continue;
                                    }
                                    let stride_dims: Vec<String> = (axis as usize + 1..rank)
                                        .filter_map(|i| shape.dim(i))
                                        .map(dim_to_msl_str)
                                        .collect();
                                    if stride_dims.is_empty() {
                                        parts.push(start.to_string());
                                    } else {
                                        parts.push(format!(
                                            "{} * {}",
                                            start,
                                            stride_dims.join(" * ")
                                        ));
                                    }
                                }
                                if parts.is_empty() { None } else { Some(parts.join(" + ")) }
                            }
                        })
                        .unwrap_or_else(|| {
                            ranges.iter().map(|(_, start, _)| start).sum::<i64>().to_string()
                        });
                    if offset_str == "0" {
                        wl!(out, "{pad}auto {v} = {rv};");
                    } else {
                        wl!(out, "{pad}auto {v} = {rv} + {offset_str};");
                    }
                },

                Op::Transpose { value } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    // Use type env to emit a real permutation loop for register tiles.
                    if let Some(tv) = type_env.get(value) {
                        let rank = tv.shape.rank();
                        if rank == 2 {
                            let m = tv.shape.dim(0).map(dim_to_msl_str).unwrap_or("M".into());
                            let n = tv.shape.dim(1).map(dim_to_msl_str).unwrap_or("N".into());
                            let t = self.msl_type_name(tv.dtype);
                            wl!(out, "{pad}{t} {v}[{m} * {n}];");
                            wl!(out, "{pad}for (uint r = 0; r < {m}; r++) {{");
                            wl!(out, "{pad}    for (uint c = 0; c < {n}; c++) {{");
                            wl!(out, "{pad}        {v}[c * {m} + r] = {rv}[r * {n} + c];");
                            wl!(out, "{pad}    }}");
                            wl!(out, "{pad}}}");
                        } else {
                            wl!(out, "{pad}// Transpose: unsupported rank {rank}");
                            wl!(out, "{pad}auto {v} = {rv};");
                        }
                    } else {
                        wl!(out, "{pad}// Transpose: caller uses transposed index strides");
                        wl!(out, "{pad}auto {v} = {rv};");
                    }
                },

                // ---- compute -------------------------------------------
                Op::BinOp { op, lhs, rhs } => {
                    let v = self.vname(vid, block, extra_names);
                    let l = self.vname(Some(*lhs), block, extra_names);
                    let r = self.vname(Some(*rhs), block, extra_names);
                    match op {
                        BinOpKind::Max | BinOpKind::Min | BinOpKind::Pow => {
                            wl!(out, "{pad}auto {v} = {}({l}, {r});", op.msl_symbol())
                        },
                        BinOpKind::And => wl!(out, "{pad}auto {v} = ({l} && {r});"),
                        BinOpKind::Or => wl!(out, "{pad}auto {v} = ({l} || {r});"),
                        BinOpKind::Xor => wl!(out, "{pad}auto {v} = ((bool){l} != (bool){r});"),
                        BinOpKind::BitAnd => wl!(out, "{pad}auto {v} = ({l} & {r});"),
                        BinOpKind::BitOr => wl!(out, "{pad}auto {v} = ({l} | {r});"),
                        BinOpKind::BitXor => wl!(out, "{pad}auto {v} = ({l} ^ {r});"),
                        BinOpKind::Shl => wl!(out, "{pad}auto {v} = ({l} << {r});"),
                        BinOpKind::Shr => wl!(out, "{pad}auto {v} = ({l} >> {r});"),
                        _ => wl!(out, "{pad}auto {v} = {l} {} {r};", op.msl_symbol()),
                    }
                },

                Op::UnaryOp { op, value } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    let expr = op.msl_emit(&rv);
                    wl!(out, "{pad}auto {v} = {expr};");
                },

                Op::Activation { kind, value } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}auto {v} = {}({rv});", kind.msl_fn());
                },

                Op::Select { cond, on_true, on_false } => {
                    let v = self.vname(vid, block, extra_names);
                    let vc = self.vname(Some(*cond), block, extra_names);
                    let vt = self.vname(Some(*on_true), block, extra_names);
                    let vf = self.vname(Some(*on_false), block, extra_names);
                    // MSL select(false_val, true_val, condition) — reversed from C ternary.
                    wl!(out, "{pad}auto {v} = select({vf}, {vt}, bool({vc}));");
                },

                Op::Broadcast { value, shape } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    let n = self.shape_nelems_str(shape);
                    let dt = type_env
                        .get(value)
                        .map(|tv| self.msl_type_name(tv.dtype))
                        .unwrap_or("float");
                    wl!(out, "{pad}{dt} {v}_data[{n}];");
                    wl!(out, "{pad}for (uint _i = 0; _i < {n}; _i++) {v}_data[_i] = {dt}({rv});");
                    wl!(out, "{pad}{dt}* {v} = {v}_data;");
                },

                Op::Dot { .. } => {
                    self.emit_tiled(out, &pad, kernel, vid)?;
                },

                Op::StrideReduce {
                    src,
                    offset,
                    stride,
                    end,
                    op: rk,
                    transform,
                    secondary_src,
                    secondary_base,
                    ..
                } => {
                    let v = self.vname(vid, block, extra_names);
                    let off = self.vname(Some(*offset), block, extra_names);
                    let st = self.vname(Some(*stride), block, extra_names);
                    let en = self.vname(Some(*end), block, extra_names);
                    let init = match rk {
                        ReduceKind::Sum | ReduceKind::Mean => "0.0f",
                        ReduceKind::Max => "-INFINITY",
                        ReduceKind::Min => "INFINITY",
                    };
                    // Build the per-element expression from the transform chain.
                    let base_elem = if let Some(sec_src) = secondary_src {
                        let base_v = self.vname(*secondary_base, block, extra_names);
                        format!("float({src}[_i]) * float({sec_src}[_i - {base_v}])")
                    } else {
                        format!("float({src}[_i])")
                    };
                    let elem_expr = match transform.as_ref().map(|v| v.as_slice()) {
                        None | Some(&[]) => base_elem,
                        Some(ops) => {
                            let mut expr = base_elem;
                            for sub_op in ops {
                                expr = match sub_op {
                                    Op::UnaryOp { op, .. } => op.msl_emit(&expr),
                                    Op::Activation { kind, .. } => {
                                        format!("{}({})", kind.msl_fn(), expr)
                                    },
                                    Op::Cast { dtype, .. } => self.emit_cast_expr(*dtype, &expr),
                                    Op::BinOp { op, rhs, .. } => {
                                        let rv = self.vname(Some(*rhs), block, extra_names);
                                        match op {
                                            BinOpKind::Mul => format!("({} * float({rv}))", expr),
                                            BinOpKind::Add => format!("({} + float({rv}))", expr),
                                            BinOpKind::Sub => format!("({} - float({rv}))", expr),
                                            BinOpKind::Div => format!("({} / float({rv}))", expr),
                                            _ => expr,
                                        }
                                    },
                                    _ => expr,
                                };
                            }
                            expr
                        },
                    };
                    // In Reduction/Tile2D modes, use `tid` and `lsize` as defaults.
                    let has_tid = matches!(kernel.mode, KernelMode::Reduction | KernelMode::Tile2D);
                    if has_tid {
                        // N_READS=4 contiguous block access (matches MLX all_reduce pattern).
                        // Each thread reads 4 consecutive elements per iteration,
                        // advancing by lsize*4 — cache-line friendly vs stride-lsize.
                        let update = match rk {
                            ReduceKind::Sum | ReduceKind::Mean => format!("{v} += {elem_expr};"),
                            ReduceKind::Max => format!("{v} = max({v}, {elem_expr});"),
                            ReduceKind::Min => format!("{v} = min({v}, {elem_expr});"),
                        };
                        wl!(out, "{pad}float {v} = {init};");
                        wl!(out, "{pad}{{");
                        wl!(out, "{pad}    uint _sz   = {en} - {off};");
                        wl!(out, "{pad}    uint _full = _sz / (lsize * 4u);");
                        wl!(
                            out,
                            "{pad}    int  _xtra = (int)_sz - (int)(_full * lsize * 4u) - (int)(tid * 4u);"
                        );
                        wl!(out, "{pad}    if (_xtra >= 4) {{ _full++; _xtra = 0; }}");
                        wl!(out, "{pad}    uint _base = {off} + tid * 4u;");
                        wl!(
                            out,
                            "{pad}    for (uint _b = 0; _b < _full; _b++, _base += lsize * 4u) {{"
                        );
                        wl!(out, "{pad}        for (uint _k = 0; _k < 4u; _k++) {{");
                        wl!(out, "{pad}            uint _i = _base + _k;");
                        wl!(out, "{pad}            {update}");
                        wl!(out, "{pad}        }}");
                        wl!(out, "{pad}    }}");
                        wl!(out, "{pad}    for (int _k = 0; _k < _xtra; _k++) {{");
                        wl!(out, "{pad}        uint _i = _base + (uint)_k;");
                        wl!(out, "{pad}        {update}");
                        wl!(out, "{pad}    }}");
                        wl!(out, "{pad}}}");
                    } else {
                        // Elementwise / Grid3D: simple strided loop, offset and stride from DSL.
                        let update = match rk {
                            ReduceKind::Sum | ReduceKind::Mean => format!("{v} += {elem_expr};"),
                            ReduceKind::Max => format!("{v} = max({v}, {elem_expr});"),
                            ReduceKind::Min => format!("{v} = min({v}, {elem_expr});"),
                        };
                        wl!(out, "{pad}float {v} = {init};");
                        wl!(out, "{pad}for (uint _i = {off}; _i < {en}; _i += {st}) {{");
                        wl!(out, "{pad}    {update}");
                        wl!(out, "{pad}}}");
                    }
                },

                Op::Reduce { value: val, axis, op: rk } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*val), block, extra_names);
                    self.emit_reduce(out, &pad, &v, &rv, *axis, *rk, hoists, kernel);
                },

                Op::Cast { value, dtype } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    // Use explicit type for BF16: Metal promotes bfloat→float in expressions,
                    // so `auto` would deduce float instead of bfloat.
                    let type_decl = self.msl_type_name(*dtype);
                    wl!(out, "{pad}{type_decl} {v} = {};", self.emit_cast_expr(*dtype, &rv));
                },

                // ---- control flow --------------------------------------
                Op::Loop { var, start, end, step, body: bid } => {
                    let s = self.vname(Some(*start), block, extra_names);
                    let e = self.vname(Some(*end), block, extra_names);
                    let st = self.vname(Some(*step), block, extra_names);
                    let vn = format!("i_{}", var.as_u32());
                    wl!(out, "{pad}for (uint {vn} = {s}; {vn} < {e}; {vn} += {st}) {{");
                    if let Some(bb) = all_blocks.get(bid) {
                        // Wire loop variable into the inner block's name map.
                        // Use high-bit sentinel (0xC000_0000 | var_id) so this key can never
                        // alias a real kernel ValueId (which are small sequential u32s).
                        let loop_var_vid = ValueId::new(0xC000_0000 | var.as_u32());
                        // Seed inner_names with parent block's named values so the loop body
                        // can resolve variables like `row_max` by their human-readable name.
                        // Apply the same "v_" prefix that vname() uses for block.names lookups
                        // so that inner_names references match the already-emitted declarations.
                        let mut inner_names: BTreeMap<ValueId, String> =
                            block.names.iter().map(|(&k, v)| (k, format!("v_{v}"))).collect();
                        inner_names.extend(extra_names.iter().map(|(&k, v)| (k, v.clone())));
                        inner_names.insert(loop_var_vid, vn.clone());
                        // Also register the legacy +1000 key so macro-generated kernels work.
                        inner_names.insert(ValueId::new(var.as_u32() + 1000), vn.clone());
                        self.emit_block(
                            bb,
                            all_blocks,
                            out,
                            indent + 1,
                            kernel,
                            type_env,
                            &inner_names,
                            hoists,
                        )?;
                    }
                    wl!(out, "{pad}}}");
                },

                // ---- escape hatch --------------------------------------
                Op::InlineMsl { source, inputs, outputs } => {
                    // Declare output variable(s) before the inline block.
                    for (oi, slot) in outputs.iter().enumerate() {
                        let out_vid = vid.map(|v| ValueId::new(v.as_u32() + oi as u32));
                        let vn = self.vname(out_vid, block, extra_names);
                        wl!(out, "{pad}{} {vn};", self.msl_type_name(slot.dtype));
                    }
                    // Bind inputs to positional aliases so inline source can reference them.
                    for (ii, inp_vid) in inputs.iter().enumerate() {
                        let inp = self.vname(Some(*inp_vid), block, extra_names);
                        wl!(out, "{pad}auto _in{ii} = {inp};");
                    }
                    for line in source.lines() {
                        wl!(out, "{pad}{line}");
                    }
                },

                // ---- fused elementwise chain ---------------------------
                Op::FusedElementwise { ops: fused_ops } => {
                    let v = self.vname(vid, block, extra_names);
                    if fused_ops.is_empty() {
                        wl!(out, "{pad}auto {v} = {{}};");
                    } else if let Some(resolved_vid) = vid {
                        let last_idx = fused_ops.len() - 1;
                        let expr = self.emit_fused_expr(
                            out,
                            &pad,
                            fused_ops,
                            block,
                            kernel,
                            type_env,
                            extra_names,
                            resolved_vid,
                            last_idx,
                        );
                        // Use explicit type for BF16: Metal promotes bfloat→float in
                        // expressions, so `auto` would deduce float instead of bfloat.
                        // With native bfloat, arithmetic always promotes to float, so
                        // wrap the expression in bfloat(...) to cast back.
                        let result_is_bf16 = type_env
                            .get(&resolved_vid)
                            .map(|tv| tv.dtype == DType::BF16)
                            .unwrap_or(false);
                        if self.config.native_bfloat && result_is_bf16 {
                            wl!(out, "{pad}bfloat {v} = bfloat({expr});");
                        } else if result_is_bf16 {
                            let bf_type = self.msl_type_name(DType::BF16);
                            wl!(out, "{pad}{bf_type} {v} = {expr};");
                        } else {
                            wl!(out, "{pad}auto {v} = {expr};");
                        }
                    }
                },

                // ---- vectorised data movement ---------------------------
                Op::VectorLoad { src, byte_offset, len } => {
                    let v = self.vname(vid, block, extra_names);
                    let bo = self.vname(Some(*byte_offset), block, extra_names);
                    let param_dtype = kernel
                        .params
                        .iter()
                        .find(|p| p.name == *src)
                        .map(|p| p.dtype)
                        .unwrap_or(DType::F32);
                    let scalar_t = param_dtype.msl_name();
                    let vec_t: String = match (*len, param_dtype) {
                        (4, DType::F16) => "half4".into(),
                        (4, DType::F32) => "float4".into(),
                        (8, DType::F16) => "half8".into(),
                        (2, _) => format!("{}2", scalar_t),
                        (4, _) => format!("{}4", scalar_t),
                        _ => format!("{}4", scalar_t),
                    };
                    wl!(
                        out,
                        "{pad}{vec_t} {v} = *((device {vec_t}*)((device {scalar_t}*){src} + {bo}));"
                    );
                },

                Op::VectorStore { dst, byte_offset, len, value } => {
                    let rv = self.vname(Some(*value), block, extra_names);
                    let bo = self.vname(Some(*byte_offset), block, extra_names);
                    let param_dtype = kernel
                        .params
                        .iter()
                        .find(|p| p.name == *dst)
                        .map(|p| p.dtype)
                        .unwrap_or(DType::F32);
                    let scalar_t = param_dtype.msl_name();
                    let vec_t: String = match (*len, param_dtype) {
                        (4, DType::F16) => "half4".into(),
                        (4, DType::F32) => "float4".into(),
                        (8, DType::F16) => "half8".into(),
                        (2, _) => format!("{}2", scalar_t),
                        (4, _) => format!("{}4", scalar_t),
                        _ => format!("{}4", scalar_t),
                    };
                    wl!(
                        out,
                        "{pad}*((device {vec_t}*)((device {scalar_t}*){dst} + {bo})) = {vec_t}({rv});"
                    );
                },

                // ---- conditional branch ----------------------------------
                Op::If { cond, then_block: tbid, else_block } => {
                    let cv = self.vname(Some(*cond), block, extra_names);
                    wl!(out, "{pad}if ({cv}) {{");
                    // Propagate parent block's named values into child blocks so that
                    // variables declared in the parent (e.g. `v_ns`, `v_val_incl`) are
                    // visible inside if/else bodies — mirrors the Loop emitter pattern.
                    let mut child_names: BTreeMap<ValueId, String> =
                        block.names.iter().map(|(&k, v)| (k, format!("v_{v}"))).collect();
                    child_names.extend(extra_names.iter().map(|(&k, v)| (k, v.clone())));
                    if let Some(tb) = all_blocks.get(tbid) {
                        self.emit_block(
                            tb,
                            all_blocks,
                            out,
                            indent + 1,
                            kernel,
                            type_env,
                            &child_names,
                            hoists,
                        )?;
                    }
                    if let Some(ebid) = else_block {
                        wl!(out, "{pad}}} else {{");
                        if let Some(eb) = all_blocks.get(ebid) {
                            self.emit_block(
                                eb,
                                all_blocks,
                                out,
                                indent + 1,
                                kernel,
                                type_env,
                                &child_names,
                                hoists,
                            )?;
                        }
                    }
                    wl!(out, "{pad}}}");
                },

                // ---- shape manipulation (zero-cost aliases) -------------
                Op::ExpandDims { value, .. } | Op::Reshape { value, .. } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}// ExpandDims/Reshape: same data, new indexing");
                    wl!(out, "{pad}auto {v} = {rv};");
                },

                Op::Cat { .. } => {
                    let v = self.vname(vid, block, extra_names);
                    wl!(out, "{pad}// Op::Cat: needs lowering pass");
                    wl!(out, "{pad}auto {v} = {{}};");
                },

                // ---- gather / scatter ------------------------------------
                Op::Gather { src, indices, .. } => {
                    let v = self.vname(vid, block, extra_names);
                    let iv = self.vname(Some(*indices), block, extra_names);
                    wl!(out, "{pad}// Op::Gather: indexed load from {src}");
                    wl!(out, "{pad}auto {v} = {src}[{iv}];");
                },

                Op::Scatter { dst, indices, value, .. } => {
                    let iv = self.vname(Some(*indices), block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}// Op::Scatter: indexed store to {dst}");
                    wl!(out, "{pad}{dst}[{iv}] = {rv};");
                },

                // ---- atomic ----------------------------------------------
                Op::Atomic { op: ak, dst, index, value } => {
                    let iv = self.vname(Some(*index), block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    let fn_name = ak.msl_fn();
                    wl!(
                        out,
                        "{pad}{fn_name}((device atomic_float*){dst} + {iv}, float({rv}), memory_order_relaxed);"
                    );
                },

                // ---- scan ------------------------------------------------
                // Lower to Metal native simd_prefix builtins (Metal 2.1+).
                // For threadgroup-wide scans (> 32 threads), falls back to a
                // two-phase approach: SIMD prefix within each warp, then a
                // second pass to add the warp totals.
                Op::Scan { value, op: rk, exclusive, .. } => {
                    let v = self.vname(vid, block, extra_names);
                    let rv = self.vname(Some(*value), block, extra_names);
                    let builtin = match (rk, exclusive) {
                        (ReduceKind::Sum, false) => "simd_prefix_inclusive_sum",
                        (ReduceKind::Sum, true) => "simd_prefix_exclusive_sum",
                        (ReduceKind::Max, false) => "simd_prefix_inclusive_max",
                        (ReduceKind::Min, false) => "simd_prefix_inclusive_min",
                        _ => "simd_prefix_inclusive_sum", // fallback
                    };
                    wl!(out, "{pad}float {v} = {builtin}(float({rv}));");
                },

                // ---- stride store (output loop for reduction kernels) ----
                Op::StrideStore { src, dst, offset, end, scalar, aux_src } => {
                    let off = self.vname(Some(*offset), block, extra_names);
                    let en = self.vname(Some(*end), block, extra_names);
                    let sc = self.vname(Some(*scalar), block, extra_names);
                    let has_tid = matches!(kernel.mode, KernelMode::Reduction | KernelMode::Tile2D);
                    let idx = if has_tid { format!("{off} + tid") } else { off.clone() };
                    wl!(out, "{pad}for (uint _i = {idx}; _i < {en}; _i += lsize) {{");
                    if let Some(aux) = aux_src {
                        // aux (e.g. weight vector w[0..N]) is indexed relative to row start
                        wl!(out, "{pad}    {dst}[_i] = {src}[_i] * {sc} * {aux}[_i - {off}];");
                    } else {
                        wl!(out, "{pad}    {dst}[_i] = {src}[_i] * {sc};");
                    }
                    wl!(out, "{pad}}}");
                },

                // ---- dequantize ------------------------------------------
                Op::Dequantize { weights, scales, zeros, group_size, bits } => {
                    let v = self.vname(vid, block, extra_names);
                    if *bits == 4 {
                        // Int4 packed as uint8 (2 values per byte).
                        // Caller must provide packed_idx in the enclosing loop.
                        wl!(out, "{pad}// Op::Dequantize (int4): inline unpack per group");
                        wl!(out, "{pad}uint {v}_packed = (uint){weights}[0];");
                        wl!(out, "{pad}float {v}_s = (float){scales}[0];");
                        wl!(out, "{pad}float {v}_z = (float){zeros}[0];");
                        wl!(
                            out,
                            "{pad}float {v}0 = ((float)(({v}_packed >> 0) & 0xF) - {v}_z) * {v}_s;"
                        );
                        wl!(
                            out,
                            "{pad}float {v}1 = ((float)(({v}_packed >> 4) & 0xF) - {v}_z) * {v}_s;"
                        );
                        wl!(
                            out,
                            "{pad}// group_size={group_size}; iterate over group in enclosing loop"
                        );
                        wl!(out, "{pad}auto {v} = {v}0; // first dequantized element");
                    } else {
                        // Int8
                        wl!(out, "{pad}// Op::Dequantize (int8)");
                        wl!(out, "{pad}float {v}_s = (float){scales}[0];");
                        wl!(out, "{pad}float {v}_z = (float){zeros}[0];");
                        wl!(out, "{pad}auto {v} = ((float)(int8_t){weights}[0] - {v}_z) * {v}_s;");
                    }
                },

                // ---- high-level ML ops (must be lowered by Pass 3) ----
                Op::FlashAttention { .. }
                | Op::SlidingWindowAttention { .. }
                | Op::RmsNorm { .. }
                | Op::GatedMlp { .. } => {
                    let v = self.vname(vid, block, extra_names);
                    wl!(
                        out,
                        "{pad}// ERROR: high-level op reached MSL emit — run Pass 3 (tile_lowering) first"
                    );
                    wl!(out, "{pad}auto {v} = {{}};");
                },

                // ---- SIMD-group / threadgroup primitives ----------------
                Op::SimdReduce { value, op } => {
                    let fn_name = match op {
                        ReduceKind::Sum | ReduceKind::Mean => "simd_sum",
                        ReduceKind::Max => "simd_max",
                        ReduceKind::Min => "simd_min",
                    };
                    let vn = self.vname(Some(*value), block, extra_names);
                    let v = self.vname(vid, block, extra_names);
                    wl!(out, "{pad}float {v} = {fn_name}({vn});");
                },

                Op::ThreadgroupAlloc { dtype, size, name } => {
                    let _v = self.vname(vid, block, extra_names);
                    wl!(out, "{pad}threadgroup {} {}[{}];", self.msl_type_name(*dtype), name, size);
                },

                Op::ThreadgroupLoad { name, index } => {
                    let idx = self.vname(Some(*index), block, extra_names);
                    let v = self.vname(vid, block, extra_names);
                    wl!(out, "{pad}float {v} = {name}[{idx}];");
                },

                Op::ThreadgroupStore { name, index, value } => {
                    let idx = self.vname(Some(*index), block, extra_names);
                    let val = self.vname(Some(*value), block, extra_names);
                    let _v = self.vname(vid, block, extra_names);
                    wl!(out, "{pad}{name}[{idx}] = {val};");
                },

                Op::Barrier => {
                    let _v = self.vname(vid, block, extra_names);
                    wl!(out, "{pad}threadgroup_barrier(mem_flags::mem_threadgroup);");
                },

                // ---- mutable local variables ----------------------------
                Op::DeclareLocal { name, value } => {
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}auto __ml_{name} = {rv};");
                },

                Op::SetLocal { name, value } => {
                    let rv = self.vname(Some(*value), block, extra_names);
                    wl!(out, "{pad}__ml_{name} = {rv};");
                },

                Op::ArgReduce { .. } => {
                    let v = self.vname(vid, block, extra_names);
                    wl!(out, "{pad}uint {v} = 0; // TODO: ArgReduce — needs buffer param");
                },

                // ---- serial prefix scan ----------------------------------
                Op::StrideScan { src, dst, offset, end, op: rk } => {
                    let off = self.vname(Some(*offset), block, extra_names);
                    let en = self.vname(Some(*end), block, extra_names);
                    let (init, combine) = match rk {
                        ReduceKind::Sum | ReduceKind::Mean => ("0.0f", "_acc + v"),
                        ReduceKind::Max => ("-INFINITY", "_acc > v ? _acc : v"),
                        ReduceKind::Min => ("INFINITY", "_acc < v ? _acc : v"),
                    };
                    wl!(out, "{pad}{{");
                    wl!(out, "{pad}    float _acc = {init};");
                    wl!(out, "{pad}    for (uint _i = {off}; _i < {en}; _i++) {{");
                    wl!(out, "{pad}        float v = float({src}[_i]);");
                    wl!(out, "{pad}        _acc = {combine};");
                    wl!(out, "{pad}        {dst}[_i] = _acc;");
                    wl!(out, "{pad}    }}");
                    wl!(out, "{pad}}}");
                },

                // ---- serial argmax/argmin --------------------------------
                Op::StrideArgReduce { src, offset, end, op: rk } => {
                    let v = self.vname(vid, block, extra_names);
                    let off = self.vname(Some(*offset), block, extra_names);
                    let en = self.vname(Some(*end), block, extra_names);
                    let (init_val, cmp) = match rk {
                        ReduceKind::Max => ("-INFINITY", ">"),
                        _ => ("INFINITY", "<"),
                    };
                    wl!(out, "{pad}uint {v};");
                    wl!(out, "{pad}{{");
                    wl!(out, "{pad}    float _best = {init_val};");
                    wl!(out, "{pad}    uint  _idx  = {off};");
                    wl!(out, "{pad}    for (uint _i = {off}; _i < {en}; _i++) {{");
                    wl!(out, "{pad}        float _v = float({src}[_i]);");
                    wl!(out, "{pad}        if (_v {cmp} _best) {{ _best = _v; _idx = _i; }}");
                    wl!(out, "{pad}    }}");
                    wl!(out, "{pad}    {v} = _idx;");
                    wl!(out, "{pad}}}");
                },
            }
        }
        Ok(())
    }

    // ---- helpers ---------------------------------------------------------

    /// Mask for internal ValueId references within FusedElementwise chains.
    const SUB_OP_FLAG: u32 = 0x8000_0000;

    /// Build a single MSL expression for a fused elementwise chain.
    /// Recursively composes expressions without intermediate variables.
    fn emit_fused_expr(
        &self,
        out: &mut String,
        _pad: &str,
        ops: &[Op],
        block: &Block,
        _kernel: &Kernel,
        _type_env: &TypeEnv,
        extra_names: &BTreeMap<ValueId, String>,
        _vid: ValueId,
        idx: usize,
    ) -> String {
        if idx >= ops.len() {
            return "0".to_string();
        }
        let sub = &ops[idx];
        let mut sub_val = |v: &ValueId| -> String {
            if v.as_u32() & Self::SUB_OP_FLAG != 0 {
                // Internal reference to a previous sub-op.
                let sub_idx = (v.as_u32() & !Self::SUB_OP_FLAG) as usize;
                self.emit_fused_expr(
                    out,
                    _pad,
                    ops,
                    block,
                    _kernel,
                    _type_env,
                    extra_names,
                    _vid,
                    sub_idx,
                )
            } else {
                self.vname(Some(*v), block, extra_names)
            }
        };
        match sub {
            Op::Cast { value, dtype } => self.emit_cast_expr(*dtype, &sub_val(value)),
            Op::UnaryOp { op, value } => op.msl_emit(&sub_val(value)),
            Op::Activation { kind, value } => {
                format!("{}({})", kind.msl_fn(), sub_val(value))
            },
            Op::BinOp { op, lhs, rhs } => match op {
                BinOpKind::Max | BinOpKind::Min => {
                    format!("{}({}, {})", op.msl_symbol(), sub_val(lhs), sub_val(rhs))
                },
                BinOpKind::And => format!("({} && {})", sub_val(lhs), sub_val(rhs)),
                BinOpKind::Or => format!("({} || {})", sub_val(lhs), sub_val(rhs)),
                BinOpKind::Xor => format!("((bool){} != (bool){})", sub_val(lhs), sub_val(rhs)),
                BinOpKind::BitAnd => format!("({} & {})", sub_val(lhs), sub_val(rhs)),
                BinOpKind::BitOr => format!("({} | {})", sub_val(lhs), sub_val(rhs)),
                BinOpKind::BitXor => format!("({} ^ {})", sub_val(lhs), sub_val(rhs)),
                _ => format!("({} {} {})", sub_val(lhs), op.msl_symbol(), sub_val(rhs)),
            },
            Op::Select { cond, on_true, on_false } => {
                format!(
                    "select({}, {}, bool({}))",
                    sub_val(on_false),
                    sub_val(on_true),
                    sub_val(cond)
                )
            },
            Op::Zeros { dtype, shape } => {
                let n = self.shape_nelems_str(shape);
                format!("{}_zeros_{}", dtype.msl_name(), n)
            },
            Op::Splat { value, dtype, .. } => fmt_float(*value, dtype),
            Op::Broadcast { value, .. } => sub_val(value),
            _ => format!("/* unhandled fused sub-op */ 0"),
        }
    }

    fn vname(
        &self,
        id: Option<ValueId>,
        block: &Block,
        extra_names: &BTreeMap<ValueId, String>,
    ) -> String {
        let Some(id) = id else {
            return "v0".to_string();
        };
        if let Some(n) = extra_names.get(&id) {
            return n.clone();
        }
        if let Some(n) = block.names.get(&id) {
            return format!("v_{n}");
        }
        format!("v{}", id.as_u32())
    }

    /// Emit a row-major flat index expression for `indices` into `param_name`.
    /// Looks up the param's shape in `kernel` to compute per-dimension strides.
    fn emit_idx(
        &self,
        indices: &[IndexExpr],
        block: &Block,
        extra_names: &BTreeMap<ValueId, String>,
        kernel: &Kernel,
        param_name: &str,
    ) -> String {
        if indices.is_empty() {
            return match kernel.mode {
                KernelMode::Elementwise => "tid".to_string(),
                KernelMode::Reduction => "tgid_x".to_string(),
                KernelMode::Grid3D => "gid.x".to_string(),
                KernelMode::Tile2D => "tid.x".to_string(),
            };
        }
        if indices.len() == 1 {
            return self.idx_expr_str(&indices[0], block, extra_names);
        }
        let param = kernel.params.iter().find(|p| p.name == param_name);
        // Strided params: use runtime stride arrays {name}_strides[d] instead of
        // computing row-major strides from the static shape. This supports non-contiguous
        // views (slices, transposes) without recompiling the kernel.
        if param.map(|p| p.kind == ParamKind::Strided).unwrap_or(false) {
            let parts: Vec<String> = indices
                .iter()
                .enumerate()
                .map(|(d, idx_expr)| {
                    let idx_str = self.idx_expr_str(idx_expr, block, extra_names);
                    format!("({idx_str}) * {param_name}_strides[{d}]")
                })
                .collect();
            return parts.join(" + ");
        }
        // Contiguous params: row-major flat index = sum(idx[d] * static_stride[d]).
        let shape = param.map(|p| &p.shape);
        let rank = shape.map(|s| s.rank()).unwrap_or(indices.len());
        let mut parts: Vec<String> = Vec::new();
        for (d, idx_expr) in indices.iter().enumerate() {
            let idx_str = self.idx_expr_str(idx_expr, block, extra_names);
            let stride: Option<String> = shape.and_then(|sh| {
                let stride_dims: Vec<String> =
                    (d + 1..rank).filter_map(|i| sh.dim(i)).map(dim_to_msl_str).collect();
                if stride_dims.is_empty() { None } else { Some(stride_dims.join(" * ")) }
            });
            match stride {
                Some(s) => parts.push(format!("({idx_str}) * {s}")),
                None => parts.push(idx_str),
            }
        }
        parts.join(" + ")
    }

    fn idx_expr_str(
        &self,
        idx: &IndexExpr,
        block: &Block,
        extra_names: &BTreeMap<ValueId, String>,
    ) -> String {
        match idx {
            IndexExpr::Value(v) => self.vname(Some(*v), block, extra_names),
            IndexExpr::Const(c) => c.to_string(),
            // Range: emit the start value; the caller loops over or vectorizes.
            IndexExpr::Range(v, _) => self.vname(Some(*v), block, extra_names),
        }
    }

    /// Dimension product string for a shape (used in array sizes and loops).
    fn shape_nelems_str(&self, shape: &Shape) -> String {
        let dims: Vec<String> = shape.iter().map(dim_to_msl_str).collect();
        if dims.is_empty() { "1".to_string() } else { dims.join(" * ") }
    }

    /// Return (declaration_string, init_lines) for a tile allocation.
    /// `fill` is the initial value (0.0 for Zeros, custom for Splat).
    fn emit_tile_alloc(
        &self,
        dtype: &DType,
        shape: &Shape,
        name: &str,
        fill: f64,
    ) -> (String, Vec<String>) {
        let t = self.msl_type_name(*dtype);
        match (shape.rank(), shape.num_elements()) {
            (0, _) | (_, Some(1)) => {
                // Scalar.
                let init = fmt_float(fill, dtype);
                (format!("{t} {name} = {init}"), vec![])
            },
            _ => {
                let n = self.shape_nelems_str(shape);
                let init = fmt_float(fill, dtype);
                let decl = format!("{t} {name}[{n}]");
                let init_loop = format!("for (uint _i = 0; _i < {n}; _i++) {name}[_i] = {init};");
                (decl, vec![init_loop])
            },
        }
    }

    /// Emit a reduction: simd_sum/max/min across the SIMD group for scalar inputs.
    fn emit_reduce(
        &self,
        out: &mut String,
        pad: &str,
        result_var: &str,
        input_var: &str,
        axis: u32,
        kind: ReduceKind,
        hoists: &mut Vec<String>,
        kernel: &Kernel,
    ) {
        // Threadgroup-scope reduction for Reduction/Tile2D modes:
        // Two-level simd_sum: intra-warp via simd_sum, inter-warp via 8-slot threadgroup mem.
        // axis=0 reduces across rows (threadgroup dimension), axis=1 across columns (SIMD group).
        let use_threadgroup = (kernel.mode == KernelMode::Reduction
            || kernel.mode == KernelMode::Tile2D)
            && axis == 0;
        if use_threadgroup {
            let tg_name = format!("{result_var}_sg");
            // 256 threads / 32 per SIMD = 8 SIMD groups max.
            hoists.push(format!("threadgroup float {tg_name}[8];"));

            let (simd_fn, pad_val) = match kind {
                ReduceKind::Sum | ReduceKind::Mean => ("simd_sum", "0.0f"),
                ReduceKind::Max => ("simd_max", "-INFINITY"),
                ReduceKind::Min => ("simd_min", "INFINITY"),
            };

            // Phase 1: intra-warp reduction via simd_sum/max/min.
            wl!(out, "{pad}float {result_var};");
            wl!(out, "{pad}{{");
            wl!(out, "{pad}    float _sv = {simd_fn}(float({input_var}));");
            // Phase 2: lane 0 of each SIMD group writes its total.
            wl!(out, "{pad}    if (simd_lane == 0) {tg_name}[simd_id] = _sv;");
            wl!(out, "{pad}    threadgroup_barrier(mem_flags::mem_threadgroup);");
            // Phase 3: first SIMD group reduces warp totals and broadcasts via [0].
            wl!(out, "{pad}    if (simd_id == 0) {{");
            wl!(
                out,
                "{pad}        float _wv = simd_lane < n_simd ? {tg_name}[simd_lane] : {pad_val};"
            );
            wl!(out, "{pad}        {tg_name}[0] = {simd_fn}(_wv);");
            wl!(out, "{pad}    }}");
            wl!(out, "{pad}    threadgroup_barrier(mem_flags::mem_threadgroup);");
            if kind == ReduceKind::Mean {
                wl!(out, "{pad}    {result_var} = {tg_name}[0] / float(lsize);");
            } else {
                wl!(out, "{pad}    {result_var} = {tg_name}[0];");
            }
            wl!(out, "{pad}}}");
            return;
        }

        // Default: SIMD-group scope reduction (Elementwise / Grid3D modes).
        match kind {
            ReduceKind::Sum => wl!(out, "{pad}float {result_var} = simd_sum(float({input_var}));"),
            ReduceKind::Max => wl!(out, "{pad}float {result_var} = simd_max(float({input_var}));"),
            ReduceKind::Min => wl!(out, "{pad}float {result_var} = simd_min(float({input_var}));"),
            ReduceKind::Mean => {
                wl!(
                    out,
                    "{pad}float {result_var} = simd_sum(float({input_var})) / float(simd_size);"
                );
            },
        }
    }

    /// Emit the full tiled matmul body (cooperative threadgroup-memory GEMM).
    /// When `use_simd_matrix` is true and we're on M3+ (Metal GPU family 9+),
    /// uses hardware-accelerated `simdgroup_multiply_accumulate` for 8×8 half tiles.
    #[allow(non_snake_case)]
    fn emit_tiled(
        &self,
        out: &mut String,
        pad: &str,
        kernel: &Kernel,
        dot_vid: Option<ValueId>,
    ) -> Result<()> {
        // Check tile annotations from SchedulePass first, fall back to MslConfig.
        let s = &self.config.tile_schedule;
        let (TM, TN, TK) = match dot_vid.and_then(|v| kernel.tile_annotations.get(&v)) {
            Some(&(tm, tn, tk)) => (tm, tn, tk),
            None if self.config.use_simd_matrix => {
                // Simdgroup path: 128 threads (4 SIMD groups in a 2x2 grid).
                // Each SIMD group covers SGM x SGN = 4 x 4 8x8 fragment blocks -> 32x32 submatrix.
                // TM=64, TN=64, TK=16: double-buffered A/B tiles → 257 barriers for K=4096.
                (64, 64, 16)
            },
            None => (s.tile_m, s.tile_n, s.tile_k),
        };
        // Simdgroup path uses 128 threads (16x8); scalar path uses TileSchedule threads.
        let (THY, THX) =
            if self.config.use_simd_matrix { (8u32, 16u32) } else { (s.threads.0, s.threads.1) };
        let (RPT, CPT) = (s.rows_per_thread, s.cols_per_thread);
        let thrds = THY * THX;

        let tensors: Vec<_> = kernel.params.iter().filter(|p| p.shape.rank() == 2).collect();
        if tensors.len() < 3 {
            wl!(out, "{pad}// emit_tiled: need >= 3 2D tensor params (a, b, c)");
            return Ok(());
        }

        let a = &tensors[0].name;
        let b = &tensors[1].name;
        let c = &tensors[2].name;
        let m = dim_name(&tensors[0].shape, 0).unwrap_or("M");
        let k = dim_name(&tensors[0].shape, 1).unwrap_or("K");
        let n = dim_name(&tensors[1].shape, 1).unwrap_or("N");

        wl!(out);
        wl!(out, "{pad}// Tiled matmul: {a}[{m}×{k}] @ {b}[{k}×{n}] → {c}[{m}×{n}]");
        wl!(out, "{pad}// TM={TM} TN={TN} TK={TK} threads={THY}×{THX} RPT={RPT} CPT={CPT}");

        if self.config.use_simd_matrix {
            self.emit_tiled_simdgroup(out, pad, a, b, c, m, k, n, TM, TN, TK, THY, THX, thrds)?;
        } else {
            self.emit_tiled_scalar(
                out, pad, a, b, c, m, k, n, TM, TN, TK, THY, THX, RPT, CPT, thrds,
            )?;
        }
        wl!(out);
        Ok(())
    }

    /// Scalar GEMM path (M1/M2): each thread computes RPT×CPT outputs via a scalar inner loop.
    #[allow(non_snake_case)]
    fn emit_tiled_scalar(
        &self,
        out: &mut String,
        pad: &str,
        a: &str,
        b: &str,
        c: &str,
        m: &str,
        k: &str,
        n: &str,
        TM: u32,
        TN: u32,
        TK: u32,
        _THY: u32,
        THX: u32,
        RPT: u32,
        CPT: u32,
        thrds: u32,
    ) -> Result<()> {
        wl!(out);
        wl!(out, "{pad}threadgroup half A_tile[{TM} * {TK}];");
        wl!(out, "{pad}threadgroup half B_tile[{TK} * {TN}];");
        wl!(out, "{pad}const uint row_start = tgid.y * {TM};");
        wl!(out, "{pad}const uint col_start = tgid.x * {TN};");
        wl!(out, "{pad}float acc[{RPT}][{CPT}];");
        wl!(
            out,
            "{pad}for (uint r = 0; r < {RPT}; r++) for (uint c = 0; c < {CPT}; c++) acc[r][c] = 0.0f;"
        );
        wl!(out);
        wl!(out, "{pad}for (uint kb = 0; kb < {k}; kb += {TK}) {{");
        wl!(out, "{pad}    for (uint i = tid.y*{THX}+tid.x; i < {TM}*{TK}; i += {thrds}) {{");
        wl!(out, "{pad}        uint r = i/{TK}, ko = kb + (i%{TK});");
        wl!(
            out,
            "{pad}        A_tile[i] = (row_start+r < {m} && ko < {k}) ? {a}[(row_start+r)*{k}+ko] : 0.0h;"
        );
        wl!(out, "{pad}    }}");
        wl!(out, "{pad}    for (uint i = tid.y*{THX}+tid.x; i < {TK}*{TN}; i += {thrds}) {{");
        wl!(out, "{pad}        uint ko = kb + (i/{TN}), c2 = i%{TN};");
        wl!(
            out,
            "{pad}        B_tile[i] = (ko < {k} && col_start+c2 < {n}) ? {b}[ko*{n}+col_start+c2] : 0.0h;"
        );
        wl!(out, "{pad}    }}");
        wl!(out, "{pad}    threadgroup_barrier(mem_flags::mem_threadgroup);");
        wl!(out, "{pad}    for (uint r = 0; r < {RPT}; r++) {{");
        wl!(out, "{pad}        uint lr = tid.y*{RPT}+r;");
        wl!(out, "{pad}        for (uint c2 = 0; c2 < {CPT}; c2++) {{");
        wl!(out, "{pad}            uint lc = tid.x*{CPT}+c2;");
        wl!(out, "{pad}            float s = 0.0f;");
        wl!(out, "{pad}            for (uint kk = 0; kk < {TK}; kk++)");
        wl!(
            out,
            "{pad}                s += float(A_tile[lr*{TK}+kk]) * float(B_tile[kk*{TN}+lc]);"
        );
        wl!(out, "{pad}            acc[r][c2] += s;");
        wl!(out, "{pad}        }}");
        wl!(out, "{pad}    }}");
        wl!(out, "{pad}    threadgroup_barrier(mem_flags::mem_threadgroup);");
        wl!(out, "{pad}}}");
        wl!(out, "{pad}for (uint r = 0; r < {RPT}; r++) {{");
        wl!(out, "{pad}    uint gr = row_start + tid.y*{RPT}+r;");
        wl!(out, "{pad}    if (gr >= {m}) continue;");
        wl!(out, "{pad}    for (uint c2 = 0; c2 < {CPT}; c2++) {{");
        wl!(out, "{pad}        uint gc = col_start + tid.x*{CPT}+c2;");
        wl!(out, "{pad}        if (gc >= {n}) continue;");
        wl!(out, "{pad}        {c}[gr*{n}+gc] = half(acc[r][c2]);");
        wl!(out, "{pad}    }}");
        wl!(out, "{pad}}}");
        Ok(())
    }

    /// Simdgroup matrix multiply path (M3+): 8×8 half-precision hardware matmul.
    /// Each 32-thread simdgroup owns one `simdgroup_half8x8` fragment of C.
    #[allow(non_snake_case)]
    fn emit_tiled_simdgroup(
        &self,
        out: &mut String,
        pad: &str,
        a: &str,
        b: &str,
        c: &str,
        m: &str,
        k: &str,
        n: &str,
        TM: u32,
        TN: u32,
        TK: u32,
        _THY: u32,
        THX: u32,
        _thrds: u32,
    ) -> Result<()> {
        // 2x2 grid of SIMD groups: sg_x = sg % 2, sg_y = sg / 2.
        // Each SIMD group covers SGM x SGN = 4 x 4 8x8 fragment blocks (32x32 submatrix).
        // TM=64, TN=64 (asserted by caller), TK=tile_k (usually 32).
        // 128 threads (THX=16, THY=8): cooperative load uses tid.y*THX+tid.x as flat index.
        const SGM: u32 = 4; // fragment rows per simdgroup
        const SGN: u32 = 4; // fragment cols per simdgroup
        const SG_COLS: u32 = 2; // simdgroup columns in the 2x2 grid

        let AB_SZ: u32 = TM * TK; // A_tile half-elements per buffer; B_tile is TK*TN = same size.
        wl!(out);
        // Double-buffer A/B tiles: halves barrier count (1 per KB iter instead of 2).
        wl!(out, "{pad}threadgroup half A_tile[2 * {TM} * {TK}];");
        wl!(out, "{pad}threadgroup half B_tile[2 * {TK} * {TN}];");
        wl!(out, "{pad}const uint sg_x = simd_group % {SG_COLS};");
        wl!(out, "{pad}const uint sg_y = simd_group / {SG_COLS};");

        // fp32 accumulators for accuracy; converted to half via per-simdgroup scratch.
        for fi in 0..SGM {
            for fj in 0..SGN {
                let idx = fi * SGN + fj;
                wl!(
                    out,
                    "{pad}simdgroup_float8x8 c{idx} = make_filled_simdgroup_matrix<float, 8, 8>(0.0f);"
                );
            }
        }

        // Per-thread fixed row/col into each tile — computed once, no integer division in loops.
        // a_flat selects a fixed column (a_col) and starting row (a_row0) for A_tile loads.
        // b_flat selects a fixed column (b_col) and starting row (b_row0) for B_tile loads.
        // 128-bit (uint4 = 8 halves) vectorized tile loads: 1 instruction per thread per tile.
        // Each of the 128 threads loads exactly TM*TK/128 = 8 halves (A) and TK*TN/128 = 8 (B).
        const VEC: u32 = 8;
        let a_vld_shift = (TK / VEC).ilog2(); // TK=16 → 1
        let a_vld_mask = TK / VEC - 1; // TK=16 → 1
        let b_vld_shift = (TN / VEC).ilog2(); // TN=64 → 3
        let b_vld_mask = TN / VEC - 1; // TN=64 → 7

        // Pre-load tile 0 into buffer 0, then double-buffer: prefetch next while doing MMA.
        wl!(out);
        wl!(out, "{pad}const uint ld_flat = tid.y*{THX}+tid.x;");
        wl!(
            out,
            "{pad}const uint a_rv = ld_flat >> {a_vld_shift}u;          // A tile row for this thread"
        );
        wl!(
            out,
            "{pad}const uint a_cv = (ld_flat & {a_vld_mask}u) << 3u;   // A tile col base (0 or 8)"
        );
        wl!(
            out,
            "{pad}const uint b_rv = ld_flat >> {b_vld_shift}u;          // B tile row for this thread"
        );
        wl!(
            out,
            "{pad}const uint b_cv = (ld_flat & {b_vld_mask}u) << 3u;   // B tile col base (0,8,..,56)"
        );
        // A tile initial load: vector fast path, scalar fallback for boundary tiles.
        wl!(out, "{pad}{{");
        wl!(out, "{pad}    const uint a_gm = tgid.y*{TM} + a_rv;");
        wl!(out, "{pad}    if (a_gm < {m} && a_cv + {VEC}u <= {k}) {{");
        wl!(
            out,
            "{pad}        *((threadgroup uint4*)(A_tile + a_rv*{TK} + a_cv)) = *((const device uint4*)({a} + a_gm*{k} + a_cv));"
        );
        wl!(out, "{pad}    }} else {{");
        wl!(
            out,
            "{pad}        for (uint _i = 0; _i < {VEC}u; _i++) A_tile[a_rv*{TK} + a_cv + _i] = (a_gm < {m} && a_cv+_i < {k}) ? {a}[a_gm*{k} + a_cv + _i] : 0.0h;"
        );
        wl!(out, "{pad}    }}");
        wl!(out, "{pad}}}");
        // B tile initial load.
        wl!(out, "{pad}{{");
        wl!(out, "{pad}    const uint b_gc = tgid.x*{TN} + b_cv;");
        wl!(out, "{pad}    if (b_rv < {k} && b_gc + {VEC}u <= {n}) {{");
        wl!(
            out,
            "{pad}        *((threadgroup uint4*)(B_tile + b_rv*{TN} + b_cv)) = *((const device uint4*)({b} + b_rv*{n} + b_gc));"
        );
        wl!(out, "{pad}    }} else {{");
        wl!(
            out,
            "{pad}        for (uint _i = 0; _i < {VEC}u; _i++) B_tile[b_rv*{TN} + b_cv + _i] = (b_rv < {k} && tgid.x*{TN}+b_cv+_i < {n}) ? {b}[b_rv*{n} + tgid.x*{TN}+b_cv+_i] : 0.0h;"
        );
        wl!(out, "{pad}    }}");
        wl!(out, "{pad}}}");
        wl!(out, "{pad}threadgroup_barrier(mem_flags::mem_threadgroup);");
        wl!(out);
        wl!(out, "{pad}uint cur_buf = 0;");
        wl!(out, "{pad}for (uint kb = 0; kb < {k}; kb += {TK}) {{");
        wl!(out, "{pad}    uint nxt_buf = cur_buf ^ 1;");
        wl!(out, "{pad}    uint ca = cur_buf * {AB_SZ};  // A_tile offset for current buf");
        wl!(out, "{pad}    uint cb = cur_buf * {AB_SZ};  // B_tile offset for current buf");
        wl!(out, "{pad}    uint na = nxt_buf * {AB_SZ};  // A_tile offset for next buf");
        wl!(out, "{pad}    uint nb = nxt_buf * {AB_SZ};  // B_tile offset for next buf");

        // Prefetch next tile (overlaps with MMA below — different threadgroup memory regions).
        wl!(out, "{pad}    if (kb + {TK} < {k}) {{");
        // A prefetch: same tile row a_rv, next column offset = kb + TK + a_cv.
        wl!(out, "{pad}        {{");
        wl!(out, "{pad}            const uint a_gm = tgid.y*{TM} + a_rv;");
        wl!(out, "{pad}            const uint a_kc = kb + {TK} + a_cv;");
        wl!(out, "{pad}            if (a_gm < {m} && a_kc + {VEC}u <= {k}) {{");
        wl!(
            out,
            "{pad}                *((threadgroup uint4*)(A_tile + na + a_rv*{TK} + a_cv)) = *((const device uint4*)({a} + a_gm*{k} + a_kc));"
        );
        wl!(out, "{pad}            }} else {{");
        wl!(
            out,
            "{pad}                for (uint _i = 0; _i < {VEC}u; _i++) A_tile[na + a_rv*{TK} + a_cv + _i] = (a_gm < {m} && a_kc+_i < {k}) ? {a}[a_gm*{k} + a_kc + _i] : 0.0h;"
        );
        wl!(out, "{pad}            }}");
        wl!(out, "{pad}        }}");
        // B prefetch: next tile row = kb + TK + b_rv, same column b_cv.
        wl!(out, "{pad}        {{");
        wl!(out, "{pad}            const uint b_kr = kb + {TK} + b_rv;");
        wl!(out, "{pad}            const uint b_gc = tgid.x*{TN} + b_cv;");
        wl!(out, "{pad}            if (b_kr < {k} && b_gc + {VEC}u <= {n}) {{");
        wl!(
            out,
            "{pad}                *((threadgroup uint4*)(B_tile + nb + b_rv*{TN} + b_cv)) = *((const device uint4*)({b} + b_kr*{n} + b_gc));"
        );
        wl!(out, "{pad}            }} else {{");
        wl!(
            out,
            "{pad}                for (uint _i = 0; _i < {VEC}u; _i++) B_tile[nb + b_rv*{TN} + b_cv + _i] = (b_kr < {k} && tgid.x*{TN}+b_cv+_i < {n}) ? {b}[b_kr*{n} + tgid.x*{TN}+b_cv+_i] : 0.0h;"
        );
        wl!(out, "{pad}            }}");
        wl!(out, "{pad}        }}");
        wl!(out, "{pad}    }}");
        wl!(out);
        wl!(out, "{pad}    // MMA on current tile.");
        wl!(out, "{pad}    for (uint kk = 0; kk < {TK}; kk += 8) {{");

        // Load all SGN b_frags once per kk step (named variables so compiler keeps them in regs).
        for fj in 0..SGN {
            wl!(out, "{pad}        simdgroup_half8x8 bv{fj};");
            wl!(
                out,
                "{pad}        simdgroup_load(bv{fj}, B_tile + cb + kk*{TN} + (sg_x*{SGN}+{fj})*8, {TN}, ulong2(0,0), false);"
            );
        }

        // For each fi: load a_frag once and MMA against all SGN b_frags.
        for fi in 0..SGM {
            wl!(out, "{pad}        simdgroup_half8x8 av{fi};");
            wl!(
                out,
                "{pad}        simdgroup_load(av{fi}, A_tile + ca + (sg_y*{SGM}+{fi})*8*{TK} + kk, {TK}, ulong2(0,0), false);"
            );
            for fj in 0..SGN {
                let idx = fi * SGN + fj;
                wl!(
                    out,
                    "{pad}        simdgroup_multiply_accumulate(c{idx}, av{fi}, bv{fj}, c{idx});"
                );
            }
        }

        wl!(out, "{pad}    }}");
        // Single barrier per iteration: syncs both prefetch writes AND simdgroup_load reads.
        wl!(out, "{pad}    threadgroup_barrier(mem_flags::mem_threadgroup);");
        wl!(out, "{pad}    cur_buf = nxt_buf;");
        wl!(out, "{pad}}}");
        wl!(out);

        // Write fp32 accumulators via per-simdgroup scratch to global half.
        // simdgroup_store with stride 8 places lane l's elements at flat positions l and l+32
        // in the 64-element buffer.  Each lane reads its own 2 positions directly — no loop.
        wl!(out, "{pad}threadgroup float sg_scratch[4 * 64];");
        wl!(out, "{pad}const uint sg_idx = sg_y * {SG_COLS} + sg_x;");
        wl!(out, "{pad}const uint row_base = tgid.y * {TM}, col_base = tgid.x * {TN};");
        let sgm8 = SGM * 8; // simdgroup row span = 32
        let sgn8 = SGN * 8; // simdgroup col span = 32
        for fi in 0..SGM {
            for fj in 0..SGN {
                let idx = fi * SGN + fj;
                let fi8 = fi * 8;
                let fj8 = fj * 8;
                wl!(
                    out,
                    "{pad}simdgroup_store(c{idx}, sg_scratch + sg_idx*64, 8, ulong2(0,0), false);"
                );
                wl!(out, "{pad}{{");
                wl!(out, "{pad}    float s0 = sg_scratch[sg_idx*64 + simd_lane];");
                wl!(out, "{pad}    float s1 = sg_scratch[sg_idx*64 + simd_lane + 32];");
                // simdgroup origin within tile + fragment offset + per-lane offset
                wl!(out, "{pad}    uint gr0 = row_base + sg_y*{sgm8} + {fi8} + simd_lane/8;");
                wl!(out, "{pad}    uint gc0 = col_base + sg_x*{sgn8} + {fj8} + simd_lane%8;");
                wl!(out, "{pad}    uint gr1 = row_base + sg_y*{sgm8} + {fi8} + (simd_lane+32)/8;");
                wl!(out, "{pad}    uint gc1 = col_base + sg_x*{sgn8} + {fj8} + (simd_lane+32)%8;");
                wl!(out, "{pad}    if (gr0 < {m} && gc0 < {n}) {c}[gr0*{n}+gc0] = half(s0);");
                wl!(out, "{pad}    if (gr1 < {m} && gc1 < {n}) {c}[gr1*{n}+gc1] = half(s1);");
                wl!(out, "{pad}}}");
            }
        }
        Ok(())
    }
}

impl Default for MslGenerator {
    fn default() -> Self { MslGenerator::new(MslConfig::default()) }
}

// ---------------------------------------------------------------------------
// Free helpers
// ---------------------------------------------------------------------------

fn dim_name(shape: &Shape, idx: usize) -> Option<&str> {
    match shape.dim(idx)? {
        Dim::ConstExpr(ce) => Some(ce.name()),
        _ => None,
    }
}

fn dim_to_msl_str(dim: &Dim) -> String {
    match dim {
        Dim::Known(n) => n.to_string(),
        Dim::ConstExpr(ce) => ce.name().to_string(),
        Dim::Any => "1".to_string(),
    }
}

fn fmt_float(v: f64, dtype: &DType) -> String {
    match dtype {
        DType::F16 => format!("{}h", v),
        DType::F32 => format!("{}f", v),
        _ => v.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use metaltile_core::{
        dtype::DType,
        ir::{BinOpKind, IndexExpr, Kernel, Op, Param, ValueId},
        shape::Shape,
    };

    use super::*;

    fn make_vadd() -> Kernel {
        let mut k = Kernel::new("vector_add");
        k.params.push(Param {
            name: "a".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: false,
            kind: Default::default(),
        });
        k.params.push(Param {
            name: "b".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: false,
            kind: Default::default(),
        });
        k.params.push(Param {
            name: "c".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: true,
            kind: Default::default(),
        });
        k.body.push_op(Op::ProgramId { axis: 0 }, ValueId::new(0));
        k.body.name_value(ValueId::new(0), "idx");
        k.body.push_op(
            Op::Load {
                src: "a".into(),
                mask: None,
                other: None,
                indices: vec![IndexExpr::Value(ValueId::new(0))],
            },
            ValueId::new(1),
        );
        k.body.name_value(ValueId::new(1), "x");
        k.body.push_op(
            Op::Load {
                src: "b".into(),
                mask: None,
                other: None,
                indices: vec![IndexExpr::Value(ValueId::new(0))],
            },
            ValueId::new(2),
        );
        k.body.name_value(ValueId::new(2), "y");
        k.body.push_op(
            Op::BinOp { op: BinOpKind::Add, lhs: ValueId::new(1), rhs: ValueId::new(2) },
            ValueId::new(3),
        );
        k.body.name_value(ValueId::new(3), "sum");
        k.body.push_op_no_result(Op::Store {
            mask: None,
            dst: "c".into(),
            indices: vec![IndexExpr::Value(ValueId::new(0))],
            value: ValueId::new(3),
        });
        k
    }

    #[test]
    fn vadd_msl_structure() {
        let k = make_vadd();
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("kernel void vector_add"), "missing kernel declaration");
        assert!(msl.contains("const device float *a [[buffer(0)]]"), "missing param a");
        assert!(msl.contains("const device float *b [[buffer(1)]]"), "missing param b");
        assert!(msl.contains("device float *c [[buffer(2)]]"), "missing output param c");
        assert!(msl.contains("uint tid [[thread_position_in_grid]]"), "missing scalar tid");
        assert!(!msl.contains("tid.x"), "scalar kernel must not use tid.x");
    }

    #[test]
    fn vadd_msl_load_store() {
        let k = make_vadd();
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("v_idx = tid"), "program_id should map to tid");
        assert!(msl.contains("a[v_idx]"), "load from a at idx");
        assert!(msl.contains("b[v_idx]"), "load from b at idx");
        assert!(msl.contains("v_x + v_y"), "add x and y");
        assert!(msl.contains("c[v_idx] = v_sum"), "store sum to c");
    }

    #[test]
    fn const_op_emits_int_literal() {
        let mut k = Kernel::new("const_test");
        k.body.push_op(Op::Const { value: 42 }, ValueId::new(0));
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("int v0 = 42"), "Const op should emit int literal");
    }

    #[test]
    fn cast_op_emits_static_cast() {
        let mut k = Kernel::new("cast_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::F16 }, ValueId::new(1));
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("static_cast<half>"), "cast to f16 should use static_cast<half>");
    }

    #[test]
    fn native_bfloat_omits_compat_preamble() {
        let mut k = Kernel::new("native_bfloat_param");
        k.params.push(Param {
            name: "a".into(),
            dtype: DType::BF16,
            shape: Shape::scalar(),
            is_output: false,
            kind: Default::default(),
        });

        let msl = MslGenerator::new(MslConfig { native_bfloat: true, ..MslConfig::default() })
            .generate(&k)
            .unwrap();

        assert!(
            !msl.contains("struct bfloat16_t"),
            "native bfloat mode must not emit the compatibility preamble"
        );
        assert!(
            msl.contains("const device bfloat *a [[buffer(0)]]"),
            "native bfloat mode should keep native buffer types"
        );
    }

    #[test]
    fn bf16_cast_uses_compat_ctor_when_native_bfloat_disabled() {
        let mut k = Kernel::new("compat_bf16_cast");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::BF16 }, ValueId::new(1));

        let msl = MslGenerator::new(MslConfig { native_bfloat: false, ..MslConfig::default() })
            .generate(&k)
            .unwrap();
        assert!(msl.contains("struct bfloat16_t"), "compat mode should emit the bfloat16_t helper");
        assert!(
            msl.contains("bfloat16_t v1 = bfloat16_t(v0);"),
            "compat mode should cast to the compatibility struct"
        );
    }

    #[test]
    fn bf16_cast_uses_native_static_cast_when_enabled() {
        let mut k = Kernel::new("native_bf16_cast");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::BF16 }, ValueId::new(1));

        let msl = MslGenerator::new(MslConfig { native_bfloat: true, ..MslConfig::default() })
            .generate(&k)
            .unwrap();
        assert!(
            !msl.contains("struct bfloat16_t"),
            "native mode should not emit the compatibility helper"
        );
        assert!(
            msl.contains("bfloat v1 = bfloat(v0);"),
            "native mode should cast directly to bfloat via constructor"
        );
    }

    #[test]
    fn unary_op_emit() {
        use metaltile_core::ir::UnaryOpKind;
        let mut k = Kernel::new("unary_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body
            .push_op(Op::UnaryOp { op: UnaryOpKind::Exp, value: ValueId::new(0) }, ValueId::new(1));
        k.body.name_value(ValueId::new(1), "r");
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("exp(v0)"), "exp unary op");
        assert!(msl.contains("v_r"), "named result");
    }

    #[test]
    fn activation_silu_emits_helper() {
        use metaltile_core::ir::ActKind;
        let mut k = Kernel::new("silu_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(
            Op::Activation { kind: ActKind::Silu, value: ValueId::new(0) },
            ValueId::new(1),
        );
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("mt_silu"), "silu helper function name");
        assert!(msl.contains("inline T mt_silu"), "silu helper definition");
    }

    #[test]
    fn select_emit() {
        let mut k = Kernel::new("select_test");
        k.body.push_op(Op::Const { value: 1 }, ValueId::new(0));
        k.body.push_op(Op::Const { value: 2 }, ValueId::new(1));
        k.body.push_op(Op::Const { value: 3 }, ValueId::new(2));
        k.body.push_op(
            Op::Select {
                cond: ValueId::new(0),
                on_true: ValueId::new(1),
                on_false: ValueId::new(2),
            },
            ValueId::new(3),
        );
        let msl = MslGenerator::default().generate(&k).unwrap();
        assert!(msl.contains("select("), "select call");
        assert!(msl.contains("bool("), "bool cast on condition");
    }

    #[test]
    fn multi_dim_load_stride() {
        use metaltile_core::{constexpr::ConstExpr, shape::Dim};
        let mut k = Kernel::new("matload_test");
        let m_ce = ConstExpr::new("M");
        let n_ce = ConstExpr::new("N");
        k.params.push(Param {
            name: "a".into(),
            dtype: DType::F32,
            shape: Shape::new([Dim::ConstExpr(m_ce.clone()), Dim::ConstExpr(n_ce.clone())]),
            is_output: false,
            kind: Default::default(),
        });
        k.params.push(Param {
            name: "out".into(),
            dtype: DType::F32,
            shape: Shape::scalar(),
            is_output: true,
            kind: Default::default(),
        });
        k.constexprs.push(metaltile_core::ir::ConstExprDecl {
            name: m_ce,
            dtype: metaltile_core::dtype::DType::U32,
            value: None,
        });
        k.constexprs.push(metaltile_core::ir::ConstExprDecl {
            name: n_ce,
            dtype: metaltile_core::dtype::DType::U32,
            value: None,
        });
        k.body.push_op(Op::Const { value: 0 }, ValueId::new(0));
        k.body.name_value(ValueId::new(0), "row");
        k.body.push_op(Op::Const { value: 0 }, ValueId::new(1));
        k.body.name_value(ValueId::new(1), "col");
        k.body.push_op(
            Op::Load {
                mask: None,
                other: None,
                src: "a".into(),
                indices: vec![IndexExpr::Value(ValueId::new(0)), IndexExpr::Value(ValueId::new(1))],
            },
            ValueId::new(2),
        );
        let msl = MslGenerator::default().generate(&k).unwrap();
        // Multi-dim load should use N as the stride for the row dimension.
        assert!(msl.contains("(v_row) * N + v_col"), "2D load must use row-major stride");
    }

    #[test]
    fn fusion_cast_exp_binop_into_single_expression() {
        use metaltile_core::ir::{BinOpKind, UnaryOpKind};

        use crate::passes::{Pass, fusion::FusionPass};

        let mut k = Kernel::new("fused_test");
        k.body.push_op(Op::Const { value: 3 }, ValueId::new(0));
        k.body.push_op(Op::Cast { value: ValueId::new(0), dtype: DType::F32 }, ValueId::new(1));
        k.body
            .push_op(Op::UnaryOp { op: UnaryOpKind::Exp, value: ValueId::new(1) }, ValueId::new(2));
        k.body.push_op(Op::Const { value: 2 }, ValueId::new(3));
        k.body.push_op(
            Op::BinOp { op: BinOpKind::Mul, lhs: ValueId::new(2), rhs: ValueId::new(3) },
            ValueId::new(4),
        );

        FusionPass.run(&mut k).unwrap();

        // After fusion, there should be a FusedElementwise op.
        let has_fused = k.body.ops.iter().any(|op| matches!(op, Op::FusedElementwise { .. }));
        assert!(has_fused, "fusion pass should create a FusedElementwise op");

        let msl = MslGenerator::default().generate(&k).unwrap();
        // The fused expression should contain both exp and mul in one line.
        assert!(
            msl.contains("exp") && msl.contains(" * "),
            "fused expression should contain exp and mul"
        );
        // Should NOT have intermediate variable declarations for v1 or v2.
        let lines: Vec<&str> = msl.lines().collect();
        let fused_line = lines.iter().find(|l| l.contains("v4")).unwrap();
        assert!(
            fused_line.contains("exp") && fused_line.contains("static_cast"),
            "single fused line should contain both exp and cast: {}",
            fused_line
        );
        assert!(!msl.contains("v1 = "), "no separate declaration for v1");
        assert!(!msl.contains("v2 = "), "no separate declaration for v2");
    }
}
